In [1]:
import pandas as pd
from src.api import cliente_api_aresep

In [2]:
centrales = cliente_api_aresep.ClienteAPIInformacionCentralesElectricas()
distribucion = cliente_api_aresep.ClienteAPITarifasElectricidadDistribucion()
medios = cliente_api_aresep.ClienteAPITarifasPreciosMedios()

In [3]:
cent = centrales.obtener_datos()
dist = distribucion.obtener_datos()
med = medios.obtener_datos()

In [4]:
dist

,id_Mes,mes,anho,fecha,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,12,Diciembre,2026,2026-12-31,COOPEALFARORUIZ,T-IN,INDUSTRIAL,e. Bloque mayor a 15 kW,7989.07,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
1,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,j. Bloque mayor a 391 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
2,12,Diciembre,2026,2026-12-31,COOPELESCA,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
3,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,g. Bloque 271-390 kWh,6521.73,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
4,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,h. Bloque 271-390 kWh,75.06,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,8,Agosto,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [5]:
med

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,2,Febrero,2026,CNFL,Alumbrado Público,0.0,4.710943e+06,2.372725e+08,2.372725e+08,50.37,50.37,I Trimestre,Distribucion,2026 1
1,2,Febrero,2026,COOPESANTOS,Residencial,49816.0,7.274936e+06,6.370842e+08,6.153566e+08,87.57,84.59,I Trimestre,Distribucion,2026 1
2,2,Febrero,2026,COOPELESCA,Residencial,108744.0,1.732532e+07,1.366746e+09,1.313023e+09,78.89,75.79,I Trimestre,Distribucion,2026 1
3,2,Febrero,2026,COOPEGUANACASTE,Residencial,82769.0,3.112899e+07,2.438780e+09,2.356539e+09,78.34,75.70,I Trimestre,Distribucion,2026 1
4,2,Febrero,2026,COOPEALFARORUIZ,Residencial,5993.0,1.080510e+06,8.020200e+07,7.501220e+07,74.23,69.42,I Trimestre,Distribucion,2026 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1

In [6]:
cent

,id_Objecto,operador,centralElectrica,fuente,provincia,canton,distrito,codigoDTA,coordenadaX,coordenadaY
0,1,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,PIRRÍS,HÍDRICA,SAN JOSÉ,ASERRÍ,LEGUA,10605,478245.3572,1.064996e+06
1,2,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,RÍO MACHO,HÍDRICA,CARTAGO,PARAÍSO,OROSI,30203,517366.1853,1.080929e+06
2,3,COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...,LOS SANTOS,EÓLICA,SAN JOSÉ,DESAMPARADOS,SAN CRISTOBAL,10308,500646.6299,1.081333e+06
3,4,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BARRO MORADO,HÍDRICA,CARTAGO,CARTAGO,AGUACALIENTE O SAN FRANCISCO,30105,511833.5816,1.086642e+06
4,5,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TUIS,HÍDRICA,CARTAGO,TURRIALBA,TUIS,30507,546945.2853,1.087182e+06
5,6,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS I,HÍDRICA,CARTAGO,PARAÍSO,SANTIAGO,30202,524409.3108,1.090933e+06
6,7,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,CACHÍ,HÍDRICA,CARTAGO,JIMÉNEZ,TUCURRIQUE,30402,527023.4928,1.091413e+06
7,8,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,P.E VALLE CENTRAL,EÓLICA,SAN JOSÉ,MORA,QUITIRRISÍ,10707,478191.4419,1.093821e+06
8,9,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS III,HÍDRICA,CARTAGO,ALVARADO,CAPELLADES,30603,523374.5489,1.094067e+06
9,10,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,OROTINA,COMBUSTIBLES FÓSILES,ALAJUELA,OROTINA,LA CEIBA,20905,426289.1148,1.095474e+06
10,11,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ANGOSTURA,HÍDRICA,CARTAGO,TURRIALBA,PAVONES,30506,539499.7142,1.097460e+06
11,12,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,VENTANAS,HÍDRICA,ALAJUELA,ALAJUELA,GUÁCIMA,20105,466687.8335,1.097537e+06
12,13,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ANONOS,HÍDRICA,SAN JOSÉ,SAN JOSÉ,MATA REDONDA,10108,487022.4350,1.098193e+06
13,14,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,RÍO SEGUNDO,HÍDRICA,ALAJUELA,ALAJUELA,RÍO SEGUNDO,20109,480217.5062,1.105914e+06
14,15,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,VENTANAS GARITA,HÍDRICA,ALAJUELA,ALAJUELA,TURRÚCARES,20111,460602.1713,1.098499e+06
15,16,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BRASIL,HÍDRICA,SAN JOSÉ,SANTA ANA,BRASIL,10906,474254.4070,1.099172e+06
16,17,HIDROELÉCTRICA RÍO LAJAS S.A.,HIDROELÉCTRICA RÍO LAJAS,HÍDRICA,CARTAGO,TURRIALBA,SANTA TERESITA,30505,540198.7393,1.099461e+06
17,18,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BELÉN,HÍDRICA,SAN JOSÉ,SANTA ANA,POZOS,10903,476727.3887,1.101393e+06
18,19,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SAN ANTONIO GAS,COMBUSTIBLES FÓSILES,SAN JOSÉ,SAN JOSÉ,URUCA,10107,482183.1622,1.101927e+06
19,20,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ELECTRIONA,HÍDRICA,SAN JOSÉ,SAN JOSÉ,URUCA,10107,480436.9376,1.102372e+06
20,21,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS II,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598679.4464,1.105087e+06
21,22,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS III,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598690.0261,1.105161e+06
22,23,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BARRANCA,COMBUSTIBLES FÓSILES,PUNTARENAS,PUNTARENAS,BARRANCA,60108,421604.5859,1.105217e+06
23,24,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,TACARES,HÍDRICA,ALAJUELA,GRECIA,TACARES,20305,462802.3639,1.105856e+06
24,25,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,JORGE MANUEL DENGO,HÍDRICA,ALAJUELA,POÁS,CARRILLOS,20804,470960.1970,1.109095e+06
25,26,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ECHANDI,HÍDRICA,ALAJUELA,SAN RAMÓN,PIEDADES SUR,20205,440541.7240,1.111824e+06
26,27,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,REVENTAZON,HÍDRICA,LIMÓN,SIQUIRRES,SIQUIRRES,70301,548950.8952,1.115093e+06
27,28,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,EL ENCANTO,HÍDRICA,PUNTARENAS,MONTES DE ORO,LA UNIÓN,60402,416808.9339,1.122957e+06
28,29,SUERKATA S. R. L.,SUERKATA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483140.1137,1.128513e+06
29,30,CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.,VARA BLANCA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483170.6635,1.128759e+06
30,31,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,GUÁPILES,COMBUSTIBLES FÓSILES,LIMÓN,POCOCÍ,JIMÉNEZ,70202,527457.5320,1.133652e+06
31,32,CONSORCIO COOPERATIVO CUBUJUQUI R L,CUBUJUQUÍ,HÍDRICA,HEREDIA,SARAPIQUÍ,LAS HORQUETAS,41003,505726.2009,1.137356e+06
32,33,COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...,CHOCOSUELAS,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,449348.7210,1.138330e+06
33,34,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TORO III (JASEC),HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,472943.5216,1.142816e+06
34,35,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TORO III,HÍDRICA,ALAJUELA,RÍO CUARTO,RÍO CUARTO,21601,472926.7947,1.143019e+06
35,36,HIDROELÉCTRICA CAÑO GRANDE S.A,CAÑO GRANDE,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469336.4577,1.143449e+06
36,37,INGENIO TABOGA S.A.,TABOGA,BIOMASA,GUANACASTE,CAÑAS,BEBEDERO,50604,370946.4330,1.144654e+06
37,38,EL EMBALSE S. A.,EL EMBALSE,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,453021.0728,1.144767e+06
38,39,HIDROVENECIA S.A.,HIDROVENECIA,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469109.6710,1.147055e+06
39,40,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,JUANILAMA,SOLAR,GUANACASTE,CARRILLO,BELÉN,50504,326218.0497,1.149650e+06
40,41,HIDROELÉCTRICA PLATANAR S.A.,PLATANAR,HÍDRICA,ALAJUELA,SAN CARLOS,FLORENCIA,21002,451519.8393,1.150570e+06
41,42,AZUCARERA EL VIEJO S. A.,EL VIEJO,BIOMASA,GUANACASTE,CARRILLO,FILADELFIA,50501,338108.1871,1.152386e+06
42,43,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIGUEL DENGO,HÍDRICA,GUANACASTE,CAÑAS,CAÑAS,50601,382182.9681,1.157889e+06
43,44,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ARENAL,HÍDRICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,390660.7250,1.158504e+06
44,45,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TEJONA,EÓLICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,391596.0507,1.163752e+06
45,46,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,COTE,HÍDRICA,ALAJUELA,GUATUSO,COTE,21503,389687.4879,1.179229e+06
46,47,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BOCA DE POZO,HÍDRICA,GUANACASTE,BAGACES,LA FORTUNA,50402,371659.0863,1.180815e+06
47,48,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,RIO NARANJO,EÓLICA,GUANACASTE,BAGACES,RÍO NARANJO,50404,379782.9926,1.181288e+06
48,49,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES V,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369500.0903,1.181625e+06
49,50,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES II,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369411.3671,1.183471e+06
50,51,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES I,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369361.7475,1.183521e+06
51,52,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES III,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,370762.3170,1.185388e+06
52,53,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SOLAR MIRAVALLES,SOLAR,GUANACASTE,BAGACES,LA FORTUNA,50402,370928.3087,1.185452e+06
53,54,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,LAS PAILAS,GEOTÉRMICA,GUANACASTE,LIBERIA,CURUBANDÉ,50105,348665.6060,1.187999e+06
54,55,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,BIJAGUA,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386320.3395,1.191191e+06
55,56,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,CANALETE,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386602.5221,1.193771e+06
56,57,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,368275.7219,1.200503e+06
57,58,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS II,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,370287.5237,1.203769e+06
58,59,SOLAR HUACAS,SOLAR HUACAS,SOLAR,GUANACASTE,SANTA CRUZ,TAMARINDO,50309,304429.7349,1.145262e+06
59,60,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,BIOMASA,GUANACASTE,CARRILLO,BELÉN,50504,326070.9793,1.149635e+06

In [7]:
from src.eda.ProcesadorEDA import ProcesadorEDA

In [13]:
procesador_dist = ProcesadorEDA()
procesador_med = ProcesadorEDA()
procesador_cent = ProcesadorEDA()

In [14]:
procesador_dist.df = dist

In [15]:
procesador.df

,id_Mes,mes,anho,fecha,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,12,Diciembre,2026,2026-12-31,COOPEALFARORUIZ,T-IN,INDUSTRIAL,e. Bloque mayor a 15 kW,7989.07,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
1,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,j. Bloque mayor a 391 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
2,12,Diciembre,2026,2026-12-31,COOPELESCA,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
3,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,g. Bloque 271-390 kWh,6521.73,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
4,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,h. Bloque 271-390 kWh,75.06,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,8,Agosto,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [16]:
procesador_med.df = med

In [17]:
procesador_med.df

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,2,Febrero,2026,CNFL,Alumbrado Público,0.0,4.710943e+06,2.372725e+08,2.372725e+08,50.37,50.37,I Trimestre,Distribucion,2026 1
1,2,Febrero,2026,COOPESANTOS,Residencial,49816.0,7.274936e+06,6.370842e+08,6.153566e+08,87.57,84.59,I Trimestre,Distribucion,2026 1
2,2,Febrero,2026,COOPELESCA,Residencial,108744.0,1.732532e+07,1.366746e+09,1.313023e+09,78.89,75.79,I Trimestre,Distribucion,2026 1
3,2,Febrero,2026,COOPEGUANACASTE,Residencial,82769.0,3.112899e+07,2.438780e+09,2.356539e+09,78.34,75.70,I Trimestre,Distribucion,2026 1
4,2,Febrero,2026,COOPEALFARORUIZ,Residencial,5993.0,1.080510e+06,8.020200e+07,7.501220e+07,74.23,69.42,I Trimestre,Distribucion,2026 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1

In [18]:
procesador_cent.df = cent

In [19]:
procesador_cent.df

,id_Objecto,operador,centralElectrica,fuente,provincia,canton,distrito,codigoDTA,coordenadaX,coordenadaY
0,1,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,PIRRÍS,HÍDRICA,SAN JOSÉ,ASERRÍ,LEGUA,10605,478245.3572,1.064996e+06
1,2,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,RÍO MACHO,HÍDRICA,CARTAGO,PARAÍSO,OROSI,30203,517366.1853,1.080929e+06
2,3,COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...,LOS SANTOS,EÓLICA,SAN JOSÉ,DESAMPARADOS,SAN CRISTOBAL,10308,500646.6299,1.081333e+06
3,4,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BARRO MORADO,HÍDRICA,CARTAGO,CARTAGO,AGUACALIENTE O SAN FRANCISCO,30105,511833.5816,1.086642e+06
4,5,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TUIS,HÍDRICA,CARTAGO,TURRIALBA,TUIS,30507,546945.2853,1.087182e+06
5,6,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS I,HÍDRICA,CARTAGO,PARAÍSO,SANTIAGO,30202,524409.3108,1.090933e+06
6,7,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,CACHÍ,HÍDRICA,CARTAGO,JIMÉNEZ,TUCURRIQUE,30402,527023.4928,1.091413e+06
7,8,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,P.E VALLE CENTRAL,EÓLICA,SAN JOSÉ,MORA,QUITIRRISÍ,10707,478191.4419,1.093821e+06
8,9,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS III,HÍDRICA,CARTAGO,ALVARADO,CAPELLADES,30603,523374.5489,1.094067e+06
9,10,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,OROTINA,COMBUSTIBLES FÓSILES,ALAJUELA,OROTINA,LA CEIBA,20905,426289.1148,1.095474e+06
10,11,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ANGOSTURA,HÍDRICA,CARTAGO,TURRIALBA,PAVONES,30506,539499.7142,1.097460e+06
11,12,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,VENTANAS,HÍDRICA,ALAJUELA,ALAJUELA,GUÁCIMA,20105,466687.8335,1.097537e+06
12,13,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ANONOS,HÍDRICA,SAN JOSÉ,SAN JOSÉ,MATA REDONDA,10108,487022.4350,1.098193e+06
13,14,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,RÍO SEGUNDO,HÍDRICA,ALAJUELA,ALAJUELA,RÍO SEGUNDO,20109,480217.5062,1.105914e+06
14,15,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,VENTANAS GARITA,HÍDRICA,ALAJUELA,ALAJUELA,TURRÚCARES,20111,460602.1713,1.098499e+06
15,16,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BRASIL,HÍDRICA,SAN JOSÉ,SANTA ANA,BRASIL,10906,474254.4070,1.099172e+06
16,17,HIDROELÉCTRICA RÍO LAJAS S.A.,HIDROELÉCTRICA RÍO LAJAS,HÍDRICA,CARTAGO,TURRIALBA,SANTA TERESITA,30505,540198.7393,1.099461e+06
17,18,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BELÉN,HÍDRICA,SAN JOSÉ,SANTA ANA,POZOS,10903,476727.3887,1.101393e+06
18,19,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SAN ANTONIO GAS,COMBUSTIBLES FÓSILES,SAN JOSÉ,SAN JOSÉ,URUCA,10107,482183.1622,1.101927e+06
19,20,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ELECTRIONA,HÍDRICA,SAN JOSÉ,SAN JOSÉ,URUCA,10107,480436.9376,1.102372e+06
20,21,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS II,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598679.4464,1.105087e+06
21,22,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS III,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598690.0261,1.105161e+06
22,23,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BARRANCA,COMBUSTIBLES FÓSILES,PUNTARENAS,PUNTARENAS,BARRANCA,60108,421604.5859,1.105217e+06
23,24,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,TACARES,HÍDRICA,ALAJUELA,GRECIA,TACARES,20305,462802.3639,1.105856e+06
24,25,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,JORGE MANUEL DENGO,HÍDRICA,ALAJUELA,POÁS,CARRILLOS,20804,470960.1970,1.109095e+06
25,26,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ECHANDI,HÍDRICA,ALAJUELA,SAN RAMÓN,PIEDADES SUR,20205,440541.7240,1.111824e+06
26,27,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,REVENTAZON,HÍDRICA,LIMÓN,SIQUIRRES,SIQUIRRES,70301,548950.8952,1.115093e+06
27,28,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,EL ENCANTO,HÍDRICA,PUNTARENAS,MONTES DE ORO,LA UNIÓN,60402,416808.9339,1.122957e+06
28,29,SUERKATA S. R. L.,SUERKATA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483140.1137,1.128513e+06
29,30,CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.,VARA BLANCA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483170.6635,1.128759e+06
30,31,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,GUÁPILES,COMBUSTIBLES FÓSILES,LIMÓN,POCOCÍ,JIMÉNEZ,70202,527457.5320,1.133652e+06
31,32,CONSORCIO COOPERATIVO CUBUJUQUI R L,CUBUJUQUÍ,HÍDRICA,HEREDIA,SARAPIQUÍ,LAS HORQUETAS,41003,505726.2009,1.137356e+06
32,33,COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...,CHOCOSUELAS,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,449348.7210,1.138330e+06
33,34,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TORO III (JASEC),HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,472943.5216,1.142816e+06
34,35,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TORO III,HÍDRICA,ALAJUELA,RÍO CUARTO,RÍO CUARTO,21601,472926.7947,1.143019e+06
35,36,HIDROELÉCTRICA CAÑO GRANDE S.A,CAÑO GRANDE,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469336.4577,1.143449e+06
36,37,INGENIO TABOGA S.A.,TABOGA,BIOMASA,GUANACASTE,CAÑAS,BEBEDERO,50604,370946.4330,1.144654e+06
37,38,EL EMBALSE S. A.,EL EMBALSE,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,453021.0728,1.144767e+06
38,39,HIDROVENECIA S.A.,HIDROVENECIA,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469109.6710,1.147055e+06
39,40,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,JUANILAMA,SOLAR,GUANACASTE,CARRILLO,BELÉN,50504,326218.0497,1.149650e+06
40,41,HIDROELÉCTRICA PLATANAR S.A.,PLATANAR,HÍDRICA,ALAJUELA,SAN CARLOS,FLORENCIA,21002,451519.8393,1.150570e+06
41,42,AZUCARERA EL VIEJO S. A.,EL VIEJO,BIOMASA,GUANACASTE,CARRILLO,FILADELFIA,50501,338108.1871,1.152386e+06
42,43,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIGUEL DENGO,HÍDRICA,GUANACASTE,CAÑAS,CAÑAS,50601,382182.9681,1.157889e+06
43,44,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ARENAL,HÍDRICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,390660.7250,1.158504e+06
44,45,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TEJONA,EÓLICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,391596.0507,1.163752e+06
45,46,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,COTE,HÍDRICA,ALAJUELA,GUATUSO,COTE,21503,389687.4879,1.179229e+06
46,47,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BOCA DE POZO,HÍDRICA,GUANACASTE,BAGACES,LA FORTUNA,50402,371659.0863,1.180815e+06
47,48,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,RIO NARANJO,EÓLICA,GUANACASTE,BAGACES,RÍO NARANJO,50404,379782.9926,1.181288e+06
48,49,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES V,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369500.0903,1.181625e+06
49,50,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES II,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369411.3671,1.183471e+06
50,51,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES I,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369361.7475,1.183521e+06
51,52,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES III,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,370762.3170,1.185388e+06
52,53,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SOLAR MIRAVALLES,SOLAR,GUANACASTE,BAGACES,LA FORTUNA,50402,370928.3087,1.185452e+06
53,54,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,LAS PAILAS,GEOTÉRMICA,GUANACASTE,LIBERIA,CURUBANDÉ,50105,348665.6060,1.187999e+06
54,55,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,BIJAGUA,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386320.3395,1.191191e+06
55,56,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,CANALETE,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386602.5221,1.193771e+06
56,57,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,368275.7219,1.200503e+06
57,58,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS II,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,370287.5237,1.203769e+06
58,59,SOLAR HUACAS,SOLAR HUACAS,SOLAR,GUANACASTE,SANTA CRUZ,TAMARINDO,50309,304429.7349,1.145262e+06
59,60,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,BIOMASA,GUANACASTE,CARRILLO,BELÉN,50504,326070.9793,1.149635e+06

In [20]:
procesador_cent.verif_consis()

({'id_Objecto': int,
  'operador': str,
  'centralElectrica': str,
  'fuente': str,
  'provincia': str,
  'canton': str,
  'distrito': str,
  'codigoDTA': str,
  'coordenadaX': float,
  'coordenadaY': float},
 {})

In [21]:
procesador_cent.param_set()

{'Numero de filas': 60,
 'Numero de columnas': 10,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 0,
 'Dataframe':     id_Objecto                                           operador  \
 0            1            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 1            2            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 2            3  COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...
 3            4  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 4            5  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 5            6  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 6            7            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 7            8             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 8            9  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 9           10            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 10          11            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 11          12             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 12          13             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 13          14             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 14          15            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 15          16             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 16          17                      HIDROELÉCTRICA RÍO LAJAS S.A.
 17          18             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 18          19            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 19          20             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 20          21            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 21          22            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 22          23            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 23          24      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 24          25      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 25          26            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 26          27            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 27          28             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 28          29                                  SUERKATA S. R. L.
 29          30           CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.
 30          31            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 31          32                CONSORCIO COOPERATIVO CUBUJUQUI R L
 32          33  COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...
 33          34  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 34          35            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 35          36                     HIDROELÉCTRICA CAÑO GRANDE S.A
 36          37                                INGENIO TABOGA S.A.
 37          38                                   EL EMBALSE S. A.
 38          39                                  HIDROVENECIA S.A.
 39          40  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 40          41                       HIDROELÉCTRICA PLATANAR S.A.
 41          42                           AZUCARERA EL VIEJO S. A.
 42          43            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 43          44            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 44          45            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 45          46             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 46          47            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 47          48  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 48          49            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 49          50            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 50          51            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 51          52            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 52          53            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 53          54            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 54          55  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 55          56  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 56          57      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 57          58      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 58          59                                       SOLAR HUACAS
 59          60          GASIFICACION RESIDUOS SOLIDOS MUNICIPALES

                              centralElectrica                fuente  \
 0                                      PIRRÍS               HÍDRICA
 1                                   RÍO MACHO               HÍDRICA
 2                                  LOS SANTOS                EÓLICA
 3                                BARRO MORADO               HÍDRICA
 4                                        TUIS               HÍDRICA
 5                                    BIRRIS I               HÍDRICA
 6                                       CACHÍ               HÍDRICA
 7                           P.E VALLE CENTRAL                EÓLICA
 8                                  BIRRIS III               HÍDRICA
 9                                     OROTINA  COMBUSTIBLES FÓSILES
 10                                  ANGOSTURA               HÍDRICA
 11                                   VENTANAS               HÍDRICA
 12                                     ANONOS               HÍDRICA
 13                                RÍO SEGUNDO               HÍDRICA
 14                            VENTANAS GARITA               HÍDRICA
 15                                     BRASIL               HÍDRICA
 16                   HIDROELÉCTRICA RÍO LAJAS               HÍDRICA
 17                                      BELÉN               HÍDRICA
 18                            SAN ANTONIO GAS  COMBUSTIBLES FÓSILES
 19                                 ELECTRIONA               HÍDRICA
 20                                MOÍN GAS II  COMBUSTIBLES FÓSILES
 21                               MOÍN GAS III  COMBUSTIBLES FÓSILES
 22                                   BARRANCA  COMBUSTIBLES FÓSILES
 23                                    TACARES               HÍDRICA
 24                         JORGE MANUEL DENGO               HÍDRICA
 25                                    ECHANDI               HÍDRICA
 26                                 REVENTAZON               HÍDRICA
 27                                 EL ENCANTO               HÍDRICA
 28                                   SUERKATA               HÍDRICA
 29                                VARA BLANCA               HÍDRICA
 30                                   GUÁPILES  COMBUSTIBLES FÓSILES
 31                                  CUBUJUQUÍ               HÍDRICA
 32                                CHOCOSUELAS               HÍDRICA
 33                           TORO III (JASEC)               HÍDRICA
 34                                   TORO III               HÍDRICA
 35                                CAÑO GRANDE               HÍDRICA
 36                                     TABOGA               BIOMASA
 37                                 EL EMBALSE               HÍDRICA
 38                               HIDROVENECIA               HÍDRICA
 39                                  JUANILAMA                 SOLAR
 40                                   PLATANAR               HÍDRICA
 41                                   EL VIEJO               BIOMASA
 42                               MIGUEL DENGO               HÍDRICA
 43                                     ARENAL               HÍDRICA
 44                                     TEJONA                EÓLICA
 45                                       COTE               HÍDRICA
 46                               BOCA DE POZO               HÍDRICA
 47                                RIO NARANJO                EÓLICA
 48                               MIRAVALLES V            GEOTÉRMICA
 49                              MIRAVALLES II            GEOTÉRMICA
 50                               MIRAVALLES I            GEOTÉRMICA
 51                             MIRAVALLES III            GEOTÉRMICA
 52                           SOLAR MIRAVALLES                 SOLAR
 53                                 LAS PAILAS            GEOTÉRMICA
 54                                    BIJAGUA               HÍDRICA
 55                                   CANALETE               HÍDRICA
 56                                 LOS NEGROS               HÍDRICA
 57                              LOS NEGROS II               HÍDRICA
 58                               SOLAR HUACAS                 SOLAR
 59  GASIFICACION RESIDUOS SOLIDOS MUNICIPALES               BIOMASA

      provincia         canton                      distrito codigoDTA  \
 0     SAN JOSÉ         ASERRÍ                         LEGUA     10605
 1      CARTAGO        PARAÍSO                         OROSI     30203
 2     SAN JOSÉ   DESAMPARADOS                 SAN CRISTOBAL     10308
 3      CARTAGO        CARTAGO  AGUACALIENTE O SAN FRANCISCO     30105
 4      CARTAGO      TURRIALBA                          TUIS     30507
 5      CARTAGO        PARAÍSO                      SANTIAGO     30202
 6      CARTAGO        JIMÉNEZ                    TUCURRIQUE     30402
 7     SAN JOSÉ           MORA                    QUITIRRISÍ     10707
 8      CARTAGO       ALVARADO                    CAPELLADES     30603
 9     ALAJUELA        OROTINA                      LA CEIBA     20905
 10     CARTAGO      TURRIALBA                       PAVONES     30506
 11    ALAJUELA       ALAJUELA                       GUÁCIMA     20105
 12    SAN JOSÉ       SAN JOSÉ                  MATA REDONDA     10108
 13    ALAJUELA       ALAJUELA                   RÍO SEGUNDO     20109
 14    ALAJUELA       ALAJUELA                    TURRÚCARES     20111
 15    SAN JOSÉ      SANTA ANA                        BRASIL     10906
 16     CARTAGO      TURRIALBA                SANTA TERESITA     30505
 17    SAN JOSÉ      SANTA ANA                         POZOS     10903
 18    SAN JOSÉ       SAN JOSÉ                         URUCA     10107
 19    SAN JOSÉ       SAN JOSÉ                         URUCA     10107
 20       LIMÓN          LIMÓN                    RÍO BLANCO     70103
 21       LIMÓN          LIMÓN                    RÍO BLANCO     70103
 22  PUNTARENAS     PUNTARENAS                      BARRANCA     60108
 23    ALAJUELA         GRECIA                       TACARES     20305
 24    ALAJUELA           POÁS                     CARRILLOS     20804
 25    ALAJUELA      SAN RAMÓN                  PIEDADES SUR     20205
 26       LIMÓN      SIQUIRRES                     SIQUIRRES     70301
 27  PUNTARENAS  MONTES DE ORO                      LA UNIÓN     60402
 28     HEREDIA        HEREDIA                    VARABLANCA     40105
 29     HEREDIA        HEREDIA                    VARABLANCA     40105
 30       LIMÓN         POCOCÍ                       JIMÉNEZ     70202
 31     HEREDIA      SARAPIQUÍ                 LAS HORQUETAS     41003
 32    ALAJUELA     SAN CARLOS                       QUESADA     21001
 33    ALAJUELA     SAN CARLOS                       VENECIA     21005
 34    ALAJUELA     RÍO CUARTO                    RÍO CUARTO     21601
 35    ALAJUELA     SAN CARLOS                       VENECIA     21005
 36  GUANACASTE          CAÑAS                      BEBEDERO     50604
 37    ALAJUELA     SAN CARLOS                       QUESADA     21001
 38    ALAJUELA     SAN CARLOS                       VENECIA     21005
 39  GUANACASTE       CARRILLO                         BELÉN     50504
 40    ALAJUELA     SAN CARLOS                     FLORENCIA     21002
 41  GUANACASTE       CARRILLO                    FILADELFIA     50501
 42  GUANACASTE          CAÑAS                         CAÑAS     50601
 43  GUANACASTE        TILARÁN                    SANTA ROSA     50804
 44  GUANACASTE        TILARÁN                    SANTA ROSA     50804
 45    ALAJUELA        GUATUSO                          COTE     21503
 46  GUANACASTE        BAGACES                    LA FORTUNA     50402
 47  GUANACASTE        BAGACES                   RÍO NARANJO     50404
 48  GUANACASTE        BAGACES                    LA FORTUNA     50402
 49  GUANACASTE        BAGACES                    LA FORTUNA     50402
 50  GUANACASTE        BAGACES                    LA FORTUNA     50402
 51  GUANACASTE        BAGACES                    LA FORTUNA     50402
 52  GUANACASTE        BAGACES                    LA FORTUNA     50402
 53  GUANACASTE        LIBERIA                     CURUBANDÉ     50105
 54    ALAJUELA          UPALA                       BIJAGUA     21304
 55    ALAJUELA          UPALA                       BIJAGUA     21304
 56    ALAJUELA          UPALA                  AGUAS CLARAS     21302
 57    ALAJUELA          UPALA                  AGUAS CLARAS     21302
 58  GUANACASTE     SANTA CRUZ                     TAMARINDO     50309
 59  GUANACASTE       CARRILLO                         BELÉN     50504

     coordenadaX   coordenadaY
 0   478245.3572  1.064996e+06
 1   517366.1853  1.080929e+06
 2   500646.6299  1.081333e+06
 3   511833.5816  1.086642e+06
 4   546945.2853  1.087182e+06
 5   524409.3108  1.090933e+06
 6   527023.4928  1.091413e+06
 7   478191.4419  1.093821e+06
 8   523374.5489  1.094067e+06
 9   426289.1148  1.095474e+06
 10  539499.7142  1.097460e+06
 11  466687.8335  1.097537e+06
 12  487022.4350  1.098193e+06
 13  480217.5062  1.105914e+06
 14  460602.1713  1.098499e+06
 15  474254.4070  1.099172e+06
 16  540198.7393  1.099461e+06
 17  476727.3887  1.101393e+06
 18  482183.1622  1.101927e+06
 19  480436.9376  1.102372e+06
 20  598679.4464  1.105087e+06
 21  598690.0261  1.105161e+06
 22  421604.5859  1.105217e+06
 23  462802.3639  1.105856e+06
 24  470960.1970  1.109095e+06
 25  440541.7240  1.111824e+06
 26  548950.8952  1.115093e+06
 27  416808.9339  1.122957e+06
 28  483140.1137  1.128513e+06
 29  483170.6635  1.128759e+06
 30  527457.5320  1.133652e+06
 31  505726.2009  1.137356e+06
 32  449348.7210  1.138330e+06
 33  472943.5216  1.142816e+06
 34  472926.7947  1.143019e+06
 35  469336.4577  1.143449e+06
 36  370946.4330  1.144654e+06
 37  453021.0728  1.144767e+06
 38  469109.6710  1.147055e+06
 39  326218.0497  1.149650e+06
 40  451519.8393  1.150570e+06
 41  338108.1871  1.152386e+06
 42  382182.9681  1.157889e+06
 43  390660.7250  1.158504e+06
 44  391596.0507  1.163752e+06
 45  389687.4879  1.179229e+06
 46  371659.0863  1.180815e+06
 47  379782.9926  1.181288e+06
 48  369500.0903  1.181625e+06
 49  369411.3671  1.183471e+06
 50  369361.7475  1.183521e+06
 51  370762.3170  1.185388e+06
 52  370928.3087  1.185452e+06
 53  348665.6060  1.187999e+06
 54  386320.3395  1.191191e+06
 55  386602.5221  1.193771e+06
 56  368275.7219  1.200503e+06
 57  370287.5237  1.203769e+06
 58  304429.7349  1.145262e+06
 59  326070.9793  1.149635e+06  }

In [23]:
procesador_med.verif_consis()

({'id_Mes': int,
  'mes': str,
  'anho': int,
  'empresa': str,
  'tipoTarifa': str,
  'abonados': float,
  'ventas': float,
  'ingresoSinCVG': float,
  'ingresoConCVG': float,
  'precioMedioSinCVG': float,
  'precioMedioConCVG': float,
  'trimestre': str,
  'sistema': str,
  'trimestral': str},
 {})

In [24]:
procesador_med.param_set()

{'Numero de filas': 148,
 'Numero de columnas': 14,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 47,
 'Dataframe':      id_Mes      mes  anho          empresa  \
 0         2  Febrero  2026             CNFL
 1         2  Febrero  2026      COOPESANTOS
 2         2  Febrero  2026       COOPELESCA
 3         2  Febrero  2026  COOPEGUANACASTE
 4         2  Febrero  2026  COOPEALFARORUIZ
 ..      ...      ...   ...              ...
 143       1    Enero  2026      COOPESANTOS
 144       1    Enero  2026       COOPELESCA
 145       1    Enero  2026  COOPEGUANACASTE
 146       1    Enero  2026             CNFL
 147       1    Enero  2026   TOTAL NACIONAL

                              tipoTarifa  abonados        ventas  \
 0                     Alumbrado Público       0.0  4.710943e+06
 1                           Residencial   49816.0  7.274936e+06
 2                           Residencial  108744.0  1.732532e+07
 3                           Residencial   82769.0  3.112899e+07
 4                           Residencial    5993.0  1.080510e+06
 ..                                  ...       ...           ...
 143                          Industrial     199.0  2.833962e+05
 144                          Industrial    1671.0  4.007982e+06
 145                          Industrial     231.0  1.341863e+06
 146                          Industrial    1354.0  4.582995e+06
 147  Ventas al servicio de Distribución       0.0  1.169327e+08

      ingresoSinCVG  ingresoConCVG  precioMedioSinCVG  precioMedioConCVG  \
 0     2.372725e+08   2.372725e+08              50.37              50.37
 1     6.370842e+08   6.153566e+08              87.57              84.59
 2     1.366746e+09   1.313023e+09              78.89              75.79
 3     2.438780e+09   2.356539e+09              78.34              75.70
 4     8.020200e+07   7.501220e+07              74.23              69.42
 ..             ...            ...                ...                ...
 143   4.507616e+07   4.427938e+07             159.06             156.25
 144   3.719325e+08   3.780300e+08              92.80              94.32
 145   1.255783e+08   1.395824e+08              93.59             104.02
 146   4.659484e+08   5.315566e+08             101.67             115.98
 147   4.754417e+09   4.524353e+09              40.66              38.69

        trimestre       sistema trimestral
 0    I Trimestre  Distribucion     2026 1
 1    I Trimestre  Distribucion     2026 1
 2    I Trimestre  Distribucion     2026 1
 3    I Trimestre  Distribucion     2026 1
 4    I Trimestre  Distribucion     2026 1
 ..           ...           ...        ...
 143  I Trimestre  Distribucion     2026 1
 144  I Trimestre  Distribucion     2026 1
 145  I Trimestre  Distribucion     2026 1
 146  I Trimestre  Distribucion     2026 1
 147  I Trimestre    Generacion     2026 1

 [148 rows x 14 columns]}

In [25]:
procesador_dist.verif_consis()

({'id_Mes': int,
  'mes': str,
  'anho': int,
  'empresa': str,
  'tipoTarifa': str,
  'descripcionTarifa': str,
  'bloque': str,
  'tarifaPromedio': float,
  'tarifa': NoneType,
  'pliego': str,
  'estructuraCostos': NoneType,
  'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp},
 {'columna': 'fecha',
  'Tipos': [pandas.Timestamp, pandas.api.typing.NaTType],
  'Pociciones': [5339, 5340]})

In [26]:
procesador_dist.param_set()

{'Numero de filas': 5532,
 'Numero de columnas': 15,
 'Porcentaje de nulos': 13.5647143890094,
 'Ceros totales': 24,
 'Dataframe':       id_Mes        mes  anho      fecha          empresa tipoTarifa  \
 0         12  Diciembre  2026 2026-12-31  COOPEALFARORUIZ       T-IN
 1         12  Diciembre  2026 2026-12-31       COOPELESCA       T-RP
 2         12  Diciembre  2026 2026-12-31       COOPELESCA       T-CO
 3         12  Diciembre  2026 2026-12-31       COOPELESCA       T-RP
 4         12  Diciembre  2026 2026-12-31       COOPELESCA       T-RP
 ...      ...        ...   ...        ...              ...        ...
 5527       7      Julio  2026        NaT               GP     T-GPEN
 5528       7      Julio  2026        NaT               GP     T-GPEN
 5529       8     Agosto  2026        NaT               GP     T-GPEN
 5530      12  Diciembre  2026        NaT               GP      T-GPE
 5531      12  Diciembre  2026        NaT               GP      T-GPE

                          descripcionTarifa  \
 0                               INDUSTRIAL
 1     Tarifa residencial modalidad prepago
 2                    COMERCIOS Y SERVICIOS
 3     Tarifa residencial modalidad prepago
 4     Tarifa residencial modalidad prepago
 ...                                    ...
 5527                        Eólicas Nuevas
 5528                        Eólicas Nuevas
 5529                        Eólicas Nuevas
 5530                    Eólicas Existentes
 5531                    Eólicas Existentes

                                               bloque  tarifaPromedio tarifa  \
 0                            e. Bloque mayor a 15 kW         7989.07   None
 1                          j. Bloque mayor a 391 kWh           87.08   None
 2     a. Consumo de Energía menor o igual a 3000 kWh           87.08   None
 3                              g. Bloque 271-390 kWh         6521.73   None
 4                              h. Bloque 271-390 kWh           75.06   None
 ...                                              ...             ...    ...
 5527                   Tarifa promedio (dólares/kWh)            0.10   None
 5528            Tarifa límite inferior (dólares/kWh)            0.04   None
 5529            Tarifa límite superior (dólares/kWh)            0.01   None
 5530                 Tarifa referencia (dólares/kWh)            0.06   None
 5531            Tarifa límite inferior (dólares/kWh)            0.02   None

                        pliego estructuraCostos numeroExpediente  \
 0     Gaceta 236, Alcance 161             None       ET-94-2025
 1     Gaceta 236, Alcance 161             None       ET-94-2025
 2     Gaceta 236, Alcance 161             None       ET-94-2025
 3     Gaceta 236, Alcance 161             None       ET-94-2025
 4     Gaceta 236, Alcance 161             None       ET-94-2025
 ...                       ...              ...              ...
 5527  Gaceta 181, Alcance 124             None      ET-051-2025
 5528  Gaceta 181, Alcance 124             None      ET-051-2025
 5529  Gaceta 181, Alcance 124             None      ET-051-2025
 5530     Gaceta 13, Alcance 9             None  RE-0002-IE-2025
 5531     Gaceta 13, Alcance 9             None  RE-0002-IE-2025

      numeroResolucion fechaPublicacion
 0     RE-0072-IE-2025       2025-12-16
 1     RE-0072-IE-2025       2025-12-16
 2     RE-0072-IE-2025       2025-12-16
 3     RE-0072-IE-2025       2025-12-16
 4     RE-0072-IE-2025       2025-12-16
 ...               ...              ...
 5527  RE-0046-IE-2025       2025-09-29
 5528  RE-0046-IE-2025       2025-09-29
 5529  RE-0046-IE-2025       2025-09-29
 5530      ET-091-2024       2025-01-22
 5531      ET-091-2024       2025-01-22

 [5532 rows x 15 columns]}

In [27]:
procesador_csv_aresep = ProcesadorEDA()
procesador_csv_aresep.csv_to_df("../data/processed/aresep_unificado_2020_2025.csv")

{'Numero de filas': 4277,
 'Numero de columnas': 13,
 'Porcentaje de nulos': 2.095286056006187,
 'Ceros totales': 0,
 'Dataframe':       Mes   Año          Empresa             Tarifa  Abonados       Ventas  \
 0      12  2020             CNFL  ALUMBRADO PÚBLICO       NaN   6992121.03
 1      12  2020  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN     40730.50
 2      12  2020  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN    714811.65
 3      12  2020       COOPELESCA  ALUMBRADO PÚBLICO       NaN    790350.77
 4      12  2020      COOPESANTOS  ALUMBRADO PÚBLICO       NaN    333997.00
 ...   ...   ...              ...                ...       ...          ...
 4272    1  2025  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN    730942.49
 4273    1  2025  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN     33873.88
 4274    1  2025             CNFL  ALUMBRADO PÚBLICO       NaN   5403943.97
 4275    1  2025             ESPH        RESIDENCIAL   84277.0  21623025.00
 4276    1  2025            JASEC        RESIDENCIAL   95027.0  22747208.00

       Ingreso sin CVG  Ingreso con CVG  Precio Medio sin CVG  \
 0        4.343615e+08     4.343615e+08                 62.12
 1        1.669136e+06     1.669136e+06                 40.98
 2        4.072282e+07     4.072282e+07                 56.97
 3        4.456738e+07     4.456738e+07                 56.39
 4        2.057422e+07     2.057422e+07                 61.60
 ...               ...              ...                   ...
 4272     4.727736e+07     4.727736e+07                 64.68
 4273     1.691662e+06     1.691662e+06                 49.94
 4274     1.995098e+08     1.995098e+08                 36.92
 4275     1.648919e+09     1.853092e+09                 76.26
 4276     1.090946e+09     1.376691e+09                 47.96

       Precio Medio con CVG     Trimestre       Sistema Trimestral
 0                    62.12  IV Trimestre  Distribucion     2020 4
 1                    40.98  IV Trimestre  Distribucion     2020 4
 2                    56.97  IV Trimestre  Distribucion     2020 4
 3                    56.39  IV Trimestre  Distribucion     2020 4
 4                    61.60  IV Trimestre  Distribucion     2020 4
 ...                    ...           ...           ...        ...
 4272                 64.68   I Trimestre  Distribucion     2025 1
 4273                 49.94   I Trimestre  Distribucion     2025 1
 4274                 36.92   I Trimestre  Distribucion     2025 1
 4275                 85.70   I Trimestre  Distribucion     2025 1
 4276                 60.52   I Trimestre  Distribucion     2025 1

 [4277 rows x 13 columns]}

In [28]:
procesador_dist.df

,id_Mes,mes,anho,fecha,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,12,Diciembre,2026,2026-12-31,COOPEALFARORUIZ,T-IN,INDUSTRIAL,e. Bloque mayor a 15 kW,7989.07,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
1,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,j. Bloque mayor a 391 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
2,12,Diciembre,2026,2026-12-31,COOPELESCA,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,87.08,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
3,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,g. Bloque 271-390 kWh,6521.73,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
4,12,Diciembre,2026,2026-12-31,COOPELESCA,T-RP,Tarifa residencial modalidad prepago,h. Bloque 271-390 kWh,75.06,None,"Gaceta 236, Alcance 161",None,ET-94-2025,RE-0072-IE-2025,2025-12-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,8,Agosto,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [29]:
procesador_csv_aresep.df

,Mes,Año,Empresa,Tarifa,Abonados,Ventas,Ingreso sin CVG,Ingreso con CVG,Precio Medio sin CVG,Precio Medio con CVG,Trimestre,Sistema,Trimestral
0,12,2020,CNFL,ALUMBRADO PÚBLICO,NaN,6992121.03,4.343615e+08,4.343615e+08,62.12,62.12,IV Trimestre,Distribucion,2020 4
1,12,2020,COOPEALFARORUIZ,ALUMBRADO PÚBLICO,NaN,40730.50,1.669136e+06,1.669136e+06,40.98,40.98,IV Trimestre,Distribucion,2020 4
2,12,2020,COOPEGUANACASTE,ALUMBRADO PÚBLICO,NaN,714811.65,4.072282e+07,4.072282e+07,56.97,56.97,IV Trimestre,Distribucion,2020 4
3,12,2020,COOPELESCA,ALUMBRADO PÚBLICO,NaN,790350.77,4.456738e+07,4.456738e+07,56.39,56.39,IV Trimestre,Distribucion,2020 4
4,12,2020,COOPESANTOS,ALUMBRADO PÚBLICO,NaN,333997.00,2.057422e+07,2.057422e+07,61.60,61.60,IV Trimestre,Distribucion,2020 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,2025,COOPEGUANACASTE,ALUMBRADO PÚBLICO,NaN,730942.49,4.727736e+07,4.727736e+07,64.68,64.68,I Trimestre,Distribucion,2025 1
4273,1,2025,COOPEALFARORUIZ,ALUMBRADO PÚBLICO,NaN,33873.88,1.691662e+06,1.691662e+06,49.94,49.94,I Trimestre,Distribucion,2025 1
4274,1,2025,CNFL,ALUMBRADO PÚBLICO,NaN,5403943.97,1.995098e+08,1.995098e+08,36.92,36.92,I Trimestre,Distribucion,2025 1
4275,1,2025,ESPH,RESIDENCIAL,84277.0,21623025.00,1.648919e+09,1.853092e+09,76.26,85.70,I Trimestre,Distribucion,2025 1
4276,1,2025,JASEC,RESIDENCIAL,95027.0,22747208.00,1.090946e+09,1.376691e+09,47.96,60.52,I Trimestre,Distribucion,2025 1

In [30]:
procesador_med.df

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,2,Febrero,2026,CNFL,Alumbrado Público,0.0,4.710943e+06,2.372725e+08,2.372725e+08,50.37,50.37,I Trimestre,Distribucion,2026 1
1,2,Febrero,2026,COOPESANTOS,Residencial,49816.0,7.274936e+06,6.370842e+08,6.153566e+08,87.57,84.59,I Trimestre,Distribucion,2026 1
2,2,Febrero,2026,COOPELESCA,Residencial,108744.0,1.732532e+07,1.366746e+09,1.313023e+09,78.89,75.79,I Trimestre,Distribucion,2026 1
3,2,Febrero,2026,COOPEGUANACASTE,Residencial,82769.0,3.112899e+07,2.438780e+09,2.356539e+09,78.34,75.70,I Trimestre,Distribucion,2026 1
4,2,Febrero,2026,COOPEALFARORUIZ,Residencial,5993.0,1.080510e+06,8.020200e+07,7.501220e+07,74.23,69.42,I Trimestre,Distribucion,2026 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1