In [1]:
from api import cliente_api_aresep

In [2]:
hidrocarburos = cliente_api_aresep.ClienteAPIHistoricoTarifasHidrocarburos()

In [3]:
hc = hidrocarburos.obtener_datos(chain=False)

In [4]:
hc

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,numeroGaceta,producto,tipoCambio,precioReferenciaInternacional,precioColonizado,costoAdquisicionDolar,...,precioTerminal,rige,limiteInferiorBanda,limiteSuperiorBanda,densidadReferencia,precioImpuestoMasa,precioFinalSinPuntoFijoMasa,margenComercializadorMasa,idSIET,observaciones
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 95,473.31091,0.000,0.00000,83.02144,...,275.76261,True,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91,473.31091,0.000,0.00000,84.09732,...,283.36466,True,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91 (pescadores),473.31091,0.000,0.00000,84.09732,...,260.06913,True,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel para uso automotriz de 50 ppm de azufre,473.31091,0.000,0.00000,103.89236,...,326.44211,True,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel uso automotriz 50 ppm azufre (pescadores),473.31091,0.000,0.00000,103.89236,...,318.74099,True,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,24,LPG -mezcla 70-30,299.38000,27.006,50.85357,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7814,NA,RRG-1088-2000,2000-02-03,8,24,Av-gas,299.38000,27.006,50.85357,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7815,NA,RRG-1088-2000,2000-02-03,8,24,Jet A- general,299.38000,27.006,50.85357,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7816,NA,RRG-1088-2000,2000-02-03,8,24,Nafta liviana,299.38000,27.006,50.85357,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7817,NA,RRG-1088-2000,2000-02-03,8,24,Nafta pesada,299.38000,27.006,50.85357,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
from eda.ProcesadorEDA import ProcesadorEDA

In [6]:
procesador_hc = ProcesadorEDA()

In [7]:
procesador_hc.df = hc

In [8]:
procesador_hc.verif_consis(chain=False)

({'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp,
  'alcanceGaceta': str,
  'numeroGaceta': int,
  'producto': str,
  'tipoCambio': float,
  'precioReferenciaInternacional': float,
  'precioColonizado': float,
  'costoAdquisicionDolar': float,
  'costoAdquisicionColones': float,
  'otrosIngresosProrrateados': float,
  'asigCruzPesc': float,
  'asigCruzMinae': float,
  'asigPolGob': float,
  'subCruzPesc': float,
  'subCruzMinae': float,
  'subPolGob': float,
  'diferencialPrecios': float,
  'liquidacionExtraordinaria': float,
  'impuestoUnico': float,
  'canon': float,
  'margenOperacion': float,
  'rendTarif': float,
  'liquidacionOrdinaria': float,
  'precioPlantelSinImpuesto': float,
  'ley9840': float,
  'precioConImpuesto': float,
  'margenComercionalizador': float,
  'precioFinalSinPuntoFijo': float,
  'margenEstacionesTerrestres': float,
  'margenEstacionesAereas': float,
  'fleteEstaciones': float,
  'margenEnvasador': float,
  'precioFinalSinIVA': float,
  'IVA': float,
  'precioFinal': float,
  'margenDistribuidos': float,
  'margenDetallista': float,
  'precioConsumidorFinalGas': float,
  'precioTerminal': float,
  'rige': str,
  'limiteInferiorBanda': float,
  'limiteSuperiorBanda': float,
  'densidadReferencia': float,
  'precioImpuestoMasa': float,
  'precioFinalSinPuntoFijoMasa': float,
  'margenComercializadorMasa': float,
  'idSIET': str,
  'observaciones': str},
 {})

In [9]:
procesador_hc.df["observaciones"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
7813    NaN
7814    NaN
7815    NaN
7816    NaN
7817    NaN
Name: observaciones, Length: 7818, dtype: str

In [10]:
procesador_hc.col_uniques(["observaciones"], chain=False)

{'observaciones': [2,
  [nan, '', 'Se hace corrección sobre el precio final y se suma 1,06']]}

In [11]:
procesador_hc.rm_col(["observaciones"], axis=1, chain=False)

{'Numero de filas': 7818,
 'Numero de columnas': 49,
 'Porcentaje de nulos': 29.20497439190565,
 'Ceros totales': 124099,
 'Dataframe':      numeroExpediente numeroResolucion fechaPublicacion alcanceGaceta  \
 0         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 1         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 2         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 3         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 4         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 ...               ...              ...              ...           ...
 7813               NA    RRG-1088-2000       2000-02-03             8
 7814               NA    RRG-1088-2000       2000-02-03             8
 7815               NA    RRG-1088-2000       2000-02-03             8
 7816               NA    RRG-1088-2000       2000-02-03             8
 7817               NA    RRG-1088-2000       2000-02-03             8

       numeroGaceta                                          producto  \
 0               69                                   Gasolina RON 95
 1               69                                   Gasolina RON 91
 2               69                      Gasolina RON 91 (pescadores)
 3               69    Diésel para uso automotriz de 50 ppm de azufre
 4               69  Diésel uso automotriz 50 ppm azufre (pescadores)
 ...            ...                                               ...
 7813            24                                 LPG -mezcla 70-30
 7814            24                                            Av-gas
 7815            24                                    Jet A- general
 7816            24                                     Nafta liviana
 7817            24                                      Nafta pesada

       tipoCambio  precioReferenciaInternacional  precioColonizado  \
 0      473.31091                          0.000           0.00000
 1      473.31091                          0.000           0.00000
 2      473.31091                          0.000           0.00000
 3      473.31091                          0.000           0.00000
 4      473.31091                          0.000           0.00000
 ...          ...                            ...               ...
 7813   299.38000                         27.006          50.85357
 7814   299.38000                         27.006          50.85357
 7815   299.38000                         27.006          50.85357
 7816   299.38000                         27.006          50.85357
 7817   299.38000                         27.006          50.85357

       costoAdquisicionDolar  ...  precioConsumidorFinalGas  precioTerminal  \
 0                  83.02144  ...                       0.0       275.76261
 1                  84.09732  ...                       0.0       283.36466
 2                  84.09732  ...                       0.0       260.06913
 3                 103.89236  ...                       0.0       326.44211
 4                 103.89236  ...                       0.0       318.74099
 ...                     ...  ...                       ...             ...
 7813                    NaN  ...                       0.0             NaN
 7814                    NaN  ...                       0.0             NaN
 7815                    NaN  ...                       0.0             NaN
 7816                    NaN  ...                       0.0             NaN
 7817                    NaN  ...                       0.0             NaN

       rige  limiteInferiorBanda  limiteSuperiorBanda  densidadReferencia  \
 0     True                  0.0                  0.0                 0.0
 1     True                  0.0                  0.0                 0.0
 2     True                  0.0                  0.0                 0.0
 3     True                  0.0                  0.0                 0.0
 4     True                  0.0                  0.0                 0.0
 ...    ...                  ...                  ...                 ...
 7813                        NaN                  NaN                 NaN
 7814                        NaN                  NaN                 NaN
 7815                        NaN                  NaN                 NaN
 7816                        NaN                  NaN                 NaN
 7817                        NaN                  NaN                 NaN

       precioImpuestoMasa  precioFinalSinPuntoFijoMasa  \
 0                    0.0                          0.0
 1                    0.0                          0.0
 2                    0.0                          0.0
 3                    0.0                          0.0
 4                    0.0                          0.0
 ...                  ...                          ...
 7813                 NaN                          NaN
 7814                 NaN                          NaN
 7815                 NaN                          NaN
 7816                 NaN                          NaN
 7817                 NaN                          NaN

       margenComercializadorMasa  idSIET
 0                           0.0     NaN
 1                           0.0     NaN
 2                           0.0     NaN
 3                           0.0     NaN
 4                           0.0     NaN
 ...                         ...     ...
 7813                        NaN     NaN
 7814                        NaN     NaN
 7815                        NaN     NaN
 7816                        NaN     NaN
 7817                        NaN     NaN

 [7818 rows x 49 columns]}

In [12]:
procesador_hc.verif_consis(chain=False)

({'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp,
  'alcanceGaceta': str,
  'numeroGaceta': int,
  'producto': str,
  'tipoCambio': float,
  'precioReferenciaInternacional': float,
  'precioColonizado': float,
  'costoAdquisicionDolar': float,
  'costoAdquisicionColones': float,
  'otrosIngresosProrrateados': float,
  'asigCruzPesc': float,
  'asigCruzMinae': float,
  'asigPolGob': float,
  'subCruzPesc': float,
  'subCruzMinae': float,
  'subPolGob': float,
  'diferencialPrecios': float,
  'liquidacionExtraordinaria': float,
  'impuestoUnico': float,
  'canon': float,
  'margenOperacion': float,
  'rendTarif': float,
  'liquidacionOrdinaria': float,
  'precioPlantelSinImpuesto': float,
  'ley9840': float,
  'precioConImpuesto': float,
  'margenComercionalizador': float,
  'precioFinalSinPuntoFijo': float,
  'margenEstacionesTerrestres': float,
  'margenEstacionesAereas': float,
  'fleteEstaciones': float,
  'margenEnvasador': float,
  'precioFinalSinIVA': float,
  'IVA': float,
  'precioFinal': float,
  'margenDistribuidos': float,
  'margenDetallista': float,
  'precioConsumidorFinalGas': float,
  'precioTerminal': float,
  'rige': str,
  'limiteInferiorBanda': float,
  'limiteSuperiorBanda': float,
  'densidadReferencia': float,
  'precioImpuestoMasa': float,
  'precioFinalSinPuntoFijoMasa': float,
  'margenComercializadorMasa': float,
  'idSIET': str},
 {})

In [13]:
procesador_hc.df['idSIET']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
7813    NaN
7814    NaN
7815    NaN
7816    NaN
7817    NaN
Name: idSIET, Length: 7818, dtype: str

In [14]:
procesador_hc.rm_col(['idSIET'], axis=1, chain=False)

{'Numero de filas': 7818,
 'Numero de columnas': 48,
 'Porcentaje de nulos': 27.90115758506012,
 'Ceros totales': 124099,
 'Dataframe':      numeroExpediente numeroResolucion fechaPublicacion alcanceGaceta  \
 0         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 1         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 2         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 3         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 4         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 ...               ...              ...              ...           ...
 7813               NA    RRG-1088-2000       2000-02-03             8
 7814               NA    RRG-1088-2000       2000-02-03             8
 7815               NA    RRG-1088-2000       2000-02-03             8
 7816               NA    RRG-1088-2000       2000-02-03             8
 7817               NA    RRG-1088-2000       2000-02-03             8

       numeroGaceta                                          producto  \
 0               69                                   Gasolina RON 95
 1               69                                   Gasolina RON 91
 2               69                      Gasolina RON 91 (pescadores)
 3               69    Diésel para uso automotriz de 50 ppm de azufre
 4               69  Diésel uso automotriz 50 ppm azufre (pescadores)
 ...            ...                                               ...
 7813            24                                 LPG -mezcla 70-30
 7814            24                                            Av-gas
 7815            24                                    Jet A- general
 7816            24                                     Nafta liviana
 7817            24                                      Nafta pesada

       tipoCambio  precioReferenciaInternacional  precioColonizado  \
 0      473.31091                          0.000           0.00000
 1      473.31091                          0.000           0.00000
 2      473.31091                          0.000           0.00000
 3      473.31091                          0.000           0.00000
 4      473.31091                          0.000           0.00000
 ...          ...                            ...               ...
 7813   299.38000                         27.006          50.85357
 7814   299.38000                         27.006          50.85357
 7815   299.38000                         27.006          50.85357
 7816   299.38000                         27.006          50.85357
 7817   299.38000                         27.006          50.85357

       costoAdquisicionDolar  ...  margenDetallista  precioConsumidorFinalGas  \
 0                  83.02144  ...               0.0                       0.0
 1                  84.09732  ...               0.0                       0.0
 2                  84.09732  ...               0.0                       0.0
 3                 103.89236  ...               0.0                       0.0
 4                 103.89236  ...               0.0                       0.0
 ...                     ...  ...               ...                       ...
 7813                    NaN  ...               0.0                       0.0
 7814                    NaN  ...               0.0                       0.0
 7815                    NaN  ...               0.0                       0.0
 7816                    NaN  ...               0.0                       0.0
 7817                    NaN  ...               0.0                       0.0

       precioTerminal  rige  limiteInferiorBanda  limiteSuperiorBanda  \
 0          275.76261  True                  0.0                  0.0
 1          283.36466  True                  0.0                  0.0
 2          260.06913  True                  0.0                  0.0
 3          326.44211  True                  0.0                  0.0
 4          318.74099  True                  0.0                  0.0
 ...              ...   ...                  ...                  ...
 7813             NaN                        NaN                  NaN
 7814             NaN                        NaN                  NaN
 7815             NaN                        NaN                  NaN
 7816             NaN                        NaN                  NaN
 7817             NaN                        NaN                  NaN

       densidadReferencia  precioImpuestoMasa  precioFinalSinPuntoFijoMasa  \
 0                    0.0                 0.0                          0.0
 1                    0.0                 0.0                          0.0
 2                    0.0                 0.0                          0.0
 3                    0.0                 0.0                          0.0
 4                    0.0                 0.0                          0.0
 ...                  ...                 ...                          ...
 7813                 NaN                 NaN                          NaN
 7814                 NaN                 NaN                          NaN
 7815                 NaN                 NaN                          NaN
 7816                 NaN                 NaN                          NaN
 7817                 NaN                 NaN                          NaN

       margenComercializadorMasa
 0                           0.0
 1                           0.0
 2                           0.0
 3                           0.0
 4                           0.0
 ...                         ...
 7813                        NaN
 7814                        NaN
 7815                        NaN
 7816                        NaN
 7817                        NaN

 [7818 rows x 48 columns]}

In [15]:
procesador_hc.verif_consis(chain=False)

({'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp,
  'alcanceGaceta': str,
  'numeroGaceta': int,
  'producto': str,
  'tipoCambio': float,
  'precioReferenciaInternacional': float,
  'precioColonizado': float,
  'costoAdquisicionDolar': float,
  'costoAdquisicionColones': float,
  'otrosIngresosProrrateados': float,
  'asigCruzPesc': float,
  'asigCruzMinae': float,
  'asigPolGob': float,
  'subCruzPesc': float,
  'subCruzMinae': float,
  'subPolGob': float,
  'diferencialPrecios': float,
  'liquidacionExtraordinaria': float,
  'impuestoUnico': float,
  'canon': float,
  'margenOperacion': float,
  'rendTarif': float,
  'liquidacionOrdinaria': float,
  'precioPlantelSinImpuesto': float,
  'ley9840': float,
  'precioConImpuesto': float,
  'margenComercionalizador': float,
  'precioFinalSinPuntoFijo': float,
  'margenEstacionesTerrestres': float,
  'margenEstacionesAereas': float,
  'fleteEstaciones': float,
  'margenEnvasador': float,
  'precioFinalSinIVA': float,
  'IVA': float,
  'precioFinal': float,
  'margenDistribuidos': float,
  'margenDetallista': float,
  'precioConsumidorFinalGas': float,
  'precioTerminal': float,
  'rige': str,
  'limiteInferiorBanda': float,
  'limiteSuperiorBanda': float,
  'densidadReferencia': float,
  'precioImpuestoMasa': float,
  'precioFinalSinPuntoFijoMasa': float,
  'margenComercializadorMasa': float},
 {})

In [16]:
procesador_hc.df[list(procesador_hc.col_nulls(chain=False).keys())]

,costoAdquisicionDolar,costoAdquisicionColones,asigPolGob,subPolGob,liquidacionExtraordinaria,liquidacionOrdinaria,ley9840,margenComercionalizador,precioFinalSinPuntoFijo,precioFinalSinIVA,IVA,precioFinal,precioConsumidorFinalGas,precioTerminal,limiteInferiorBanda,limiteSuperiorBanda,densidadReferencia,precioImpuestoMasa,precioFinalSinPuntoFijoMasa,margenComercializadorMasa
0,83.02144,247.15828,0.0,0.0,0.0264,0.0,0.0,3.74577,564.85385,630.56208,1.66,632.0,0.0,275.76261,0.0,0.0,0.0,0.0,0.0,0.0
1,84.09732,250.36123,0.0,0.0,0.7533,0.0,0.0,3.74577,560.20589,625.91412,1.66,628.0,0.0,283.36466,0.0,0.0,0.0,0.0,0.0,0.0
2,84.09732,250.36123,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,NaN,0.00,NaN,0.0,260.06913,0.0,0.0,0.0,0.0,0.0,0.0
3,103.89236,309.29189,0.0,0.0,0.1887,0.0,0.0,3.74577,497.53335,563.24158,1.66,565.0,0.0,326.44211,0.0,0.0,0.0,0.0,0.0,0.0
4,103.89236,309.29189,0.0,0.0,0.0000,0.0,0.0,0.00000,0.00000,NaN,0.00,NaN,0.0,318.74099,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.40000,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186.50000,NaN,NaN,191.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.30000,NaN,NaN,109.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.40000,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.40000,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
lista_hc = list(procesador_hc.col_nulls(reverse=True, chain=False).keys())

In [18]:
lista_hc.append("precioConsumidorFinalGas")

In [19]:
lista_hc.append("precioFinal")

In [20]:
lista_hc.append("precioFinalSinPuntoFijo")

In [21]:
procesador_hc.df[lista_hc]

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,numeroGaceta,producto,tipoCambio,precioReferenciaInternacional,precioColonizado,otrosIngresosProrrateados,...,margenEstacionesTerrestres,margenEstacionesAereas,fleteEstaciones,margenEnvasador,margenDistribuidos,margenDetallista,rige,precioConsumidorFinalGas,precioFinal,precioFinalSinPuntoFijo
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 95,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,632.0,564.85385
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,628.0,560.20589
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91 (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,NaN,0.00000
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel para uso automotriz de 50 ppm de azufre,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,565.0,497.53335
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel uso automotriz 50 ppm azufre (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,NaN,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,24,LPG -mezcla 70-30,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,69.40000
7814,NA,RRG-1088-2000,2000-02-03,8,24,Av-gas,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,191.1,186.50000
7815,NA,RRG-1088-2000,2000-02-03,8,24,Jet A- general,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,109.9,105.30000
7816,NA,RRG-1088-2000,2000-02-03,8,24,Nafta liviana,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,101.40000
7817,NA,RRG-1088-2000,2000-02-03,8,24,Nafta pesada,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,99.40000

In [22]:
df = procesador_hc.df[lista_hc]

In [23]:
procesador_hc.df

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,numeroGaceta,producto,tipoCambio,precioReferenciaInternacional,precioColonizado,costoAdquisicionDolar,...,margenDetallista,precioConsumidorFinalGas,precioTerminal,rige,limiteInferiorBanda,limiteSuperiorBanda,densidadReferencia,precioImpuestoMasa,precioFinalSinPuntoFijoMasa,margenComercializadorMasa
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 95,473.31091,0.000,0.00000,83.02144,...,0.0,0.0,275.76261,True,0.0,0.0,0.0,0.0,0.0,0.0
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91,473.31091,0.000,0.00000,84.09732,...,0.0,0.0,283.36466,True,0.0,0.0,0.0,0.0,0.0,0.0
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91 (pescadores),473.31091,0.000,0.00000,84.09732,...,0.0,0.0,260.06913,True,0.0,0.0,0.0,0.0,0.0,0.0
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel para uso automotriz de 50 ppm de azufre,473.31091,0.000,0.00000,103.89236,...,0.0,0.0,326.44211,True,0.0,0.0,0.0,0.0,0.0,0.0
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel uso automotriz 50 ppm azufre (pescadores),473.31091,0.000,0.00000,103.89236,...,0.0,0.0,318.74099,True,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,24,LPG -mezcla 70-30,299.38000,27.006,50.85357,NaN,...,0.0,0.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
7814,NA,RRG-1088-2000,2000-02-03,8,24,Av-gas,299.38000,27.006,50.85357,NaN,...,0.0,0.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
7815,NA,RRG-1088-2000,2000-02-03,8,24,Jet A- general,299.38000,27.006,50.85357,NaN,...,0.0,0.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
7816,NA,RRG-1088-2000,2000-02-03,8,24,Nafta liviana,299.38000,27.006,50.85357,NaN,...,0.0,0.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
7817,NA,RRG-1088-2000,2000-02-03,8,24,Nafta pesada,299.38000,27.006,50.85357,NaN,...,0.0,0.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
procesador_hc.df = procesador_hc.df[lista_hc]

In [25]:
procesador_hc.df

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,numeroGaceta,producto,tipoCambio,precioReferenciaInternacional,precioColonizado,otrosIngresosProrrateados,...,margenEstacionesTerrestres,margenEstacionesAereas,fleteEstaciones,margenEnvasador,margenDistribuidos,margenDetallista,rige,precioConsumidorFinalGas,precioFinal,precioFinalSinPuntoFijo
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 95,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,632.0,564.85385
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,628.0,560.20589
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91 (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,NaN,0.00000
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel para uso automotriz de 50 ppm de azufre,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,565.0,497.53335
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel uso automotriz 50 ppm azufre (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,NaN,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,24,LPG -mezcla 70-30,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,69.40000
7814,NA,RRG-1088-2000,2000-02-03,8,24,Av-gas,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,191.1,186.50000
7815,NA,RRG-1088-2000,2000-02-03,8,24,Jet A- general,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,109.9,105.30000
7816,NA,RRG-1088-2000,2000-02-03,8,24,Nafta liviana,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,101.40000
7817,NA,RRG-1088-2000,2000-02-03,8,24,Nafta pesada,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,99.40000

In [26]:
procesador_hc.verif_consis(chain=False)

({'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp,
  'alcanceGaceta': str,
  'numeroGaceta': int,
  'producto': str,
  'tipoCambio': float,
  'precioReferenciaInternacional': float,
  'precioColonizado': float,
  'otrosIngresosProrrateados': float,
  'asigCruzPesc': float,
  'asigCruzMinae': float,
  'subCruzPesc': float,
  'subCruzMinae': float,
  'diferencialPrecios': float,
  'impuestoUnico': float,
  'canon': float,
  'margenOperacion': float,
  'rendTarif': float,
  'precioPlantelSinImpuesto': float,
  'precioConImpuesto': float,
  'margenEstacionesTerrestres': float,
  'margenEstacionesAereas': float,
  'fleteEstaciones': float,
  'margenEnvasador': float,
  'margenDistribuidos': float,
  'margenDetallista': float,
  'rige': str,
  'precioConsumidorFinalGas': float,
  'precioFinal': float,
  'precioFinalSinPuntoFijo': float},
 {})

In [27]:
procesador_hc.param_set()

{'Numero de filas': 7818,
 'Numero de columnas': 31,
 'Porcentaje de nulos': 0.32431361869630876,
 'Ceros totales': 105605,
 'Dataframe':      numeroExpediente numeroResolucion fechaPublicacion alcanceGaceta  \
 0         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 1         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 2         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 3         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 4         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 ...               ...              ...              ...           ...
 7813               NA    RRG-1088-2000       2000-02-03             8
 7814               NA    RRG-1088-2000       2000-02-03             8
 7815               NA    RRG-1088-2000       2000-02-03             8
 7816               NA    RRG-1088-2000       2000-02-03             8
 7817               NA    RRG-1088-2000       2000-02-03             8

       numeroGaceta                                          producto  \
 0               69                                   Gasolina RON 95
 1               69                                   Gasolina RON 91
 2               69                      Gasolina RON 91 (pescadores)
 3               69    Diésel para uso automotriz de 50 ppm de azufre
 4               69  Diésel uso automotriz 50 ppm azufre (pescadores)
 ...            ...                                               ...
 7813            24                                 LPG -mezcla 70-30
 7814            24                                            Av-gas
 7815            24                                    Jet A- general
 7816            24                                     Nafta liviana
 7817            24                                      Nafta pesada

       tipoCambio  precioReferenciaInternacional  precioColonizado  \
 0      473.31091                          0.000           0.00000
 1      473.31091                          0.000           0.00000
 2      473.31091                          0.000           0.00000
 3      473.31091                          0.000           0.00000
 4      473.31091                          0.000           0.00000
 ...          ...                            ...               ...
 7813   299.38000                         27.006          50.85357
 7814   299.38000                         27.006          50.85357
 7815   299.38000                         27.006          50.85357
 7816   299.38000                         27.006          50.85357
 7817   299.38000                         27.006          50.85357

       otrosIngresosProrrateados  ...  margenEstacionesTerrestres  \
 0                           0.0  ...                      56.681
 1                           0.0  ...                      56.681
 2                           0.0  ...                       0.000
 3                           0.0  ...                      56.681
 4                           0.0  ...                       0.000
 ...                         ...  ...                         ...
 7813                        0.0  ...                       0.000
 7814                        0.0  ...                       0.000
 7815                        0.0  ...                       0.000
 7816                        0.0  ...                       0.000
 7817                        0.0  ...                       0.000

       margenEstacionesAereas  fleteEstaciones  margenEnvasador  \
 0                        0.0           12.773              0.0
 1                        0.0           12.773              0.0
 2                        0.0            0.000              0.0
 3                        0.0           12.773              0.0
 4                        0.0            0.000              0.0
 ...                      ...              ...              ...
 7813                     0.0            0.000              0.0
 7814                     0.0            0.000              0.0
 7815                     0.0            0.000              0.0
 7816                     0.0            0.000              0.0
 7817                     0.0            0.000              0.0

       margenDistribuidos  margenDetallista  rige  precioConsumidorFinalGas  \
 0                    0.0               0.0  True                       0.0
 1                    0.0               0.0  True                       0.0
 2                    0.0               0.0  True                       0.0
 3                    0.0               0.0  True                       0.0
 4                    0.0               0.0  True                       0.0
 ...                  ...               ...   ...                       ...
 7813                 0.0               0.0                             0.0
 7814                 0.0               0.0                             0.0
 7815                 0.0               0.0                             0.0
 7816                 0.0               0.0                             0.0
 7817                 0.0               0.0                             0.0

       precioFinal  precioFinalSinPuntoFijo
 0           632.0                564.85385
 1           628.0                560.20589
 2             NaN                  0.00000
 3           565.0                497.53335
 4             NaN                  0.00000
 ...           ...                      ...
 7813          0.0                 69.40000
 7814        191.1                186.50000
 7815        109.9                105.30000
 7816          0.0                101.40000
 7817          0.0                 99.40000

 [7818 rows x 31 columns]}

In [28]:
procesador_hc.numeric_col(chain=False)

,numeroGaceta,tipoCambio,precioReferenciaInternacional,precioColonizado,otrosIngresosProrrateados,asigCruzPesc,asigCruzMinae,subCruzPesc,subCruzMinae,diferencialPrecios,...,precioConImpuesto,margenEstacionesTerrestres,margenEstacionesAereas,fleteEstaciones,margenEnvasador,margenDistribuidos,margenDetallista,precioConsumidorFinalGas,precioFinal,precioFinalSinPuntoFijo
0,69,473.31091,0.000,0.00000,0.0,0.09513,13.59546,0.0000,0.0,-5.82370,...,561.10808,56.681,0.0,12.773,0.0,0.0,0.0,0.0,632.0,564.85385
1,69,473.31091,0.000,0.00000,0.0,0.09513,13.59546,0.0000,0.0,-2.66370,...,556.46012,56.681,0.0,12.773,0.0,0.0,0.0,0.0,628.0,560.20589
2,69,473.31091,0.000,0.00000,0.0,0.00000,0.00000,-14.8694,0.0,0.00000,...,260.06913,0.000,0.0,0.000,0.0,0.0,0.0,0.0,NaN,0.00000
3,69,473.31091,0.000,0.00000,0.0,0.09513,13.59546,0.0000,0.0,-13.62870,...,493.78758,56.681,0.0,12.773,0.0,0.0,0.0,0.0,565.0,497.53335
4,69,473.31091,0.000,0.00000,0.0,0.00000,0.00000,-13.4120,0.0,0.00000,...,318.74099,0.000,0.0,0.000,0.0,0.0,0.0,0.0,NaN,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,24,299.38000,27.006,50.85357,0.0,0.00000,0.00000,0.0000,0.0,-1.22657,...,64.49100,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,69.40000
7814,24,299.38000,27.006,50.85357,0.0,0.00000,0.00000,0.0000,0.0,52.66743,...,181.61000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,191.1,186.50000
7815,24,299.38000,27.006,50.85357,0.0,0.00000,0.00000,0.0000,0.0,16.38243,...,100.47900,0.000,0.0,0.000,0.0,0.0,0.0,0.0,109.9,105.30000
7816,24,299.38000,27.006,50.85357,0.0,0.00000,0.00000,0.0000,0.0,35.13543,...,97.16700,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,101.40000
7817,24,299.38000,27.006,50.85357,0.0,0.00000,0.00000,0.0000,0.0,33.40643,...,95.21300,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,99.40000

In [29]:
procesador_hc.df[procesador_hc.df.duplicated(keep=False)]

Empty DataFrame
Columns: [numeroExpediente, numeroResolucion, fechaPublicacion, alcanceGaceta, numeroGaceta, producto, tipoCambio, precioReferenciaInternacional, precioColonizado, otrosIngresosProrrateados, asigCruzPesc, asigCruzMinae, subCruzPesc, subCruzMinae, diferencialPrecios, impuestoUnico, canon, margenOperacion, rendTarif, precioPlantelSinImpuesto, precioConImpuesto, margenEstacionesTerrestres, margenEstacionesAereas, fleteEstaciones, margenEnvasador, margenDistribuidos, margenDetallista, rige, precioConsumidorFinalGas, precioFinal, precioFinalSinPuntoFijo]
Index: []

[0 rows x 31 columns]

In [30]:
num_col = list(procesador_hc.numeric_col(chain=False).columns.values)
num_col

['numeroGaceta',
 'tipoCambio',
 'precioReferenciaInternacional',
 'precioColonizado',
 'otrosIngresosProrrateados',
 'asigCruzPesc',
 'asigCruzMinae',
 'subCruzPesc',
 'subCruzMinae',
 'diferencialPrecios',
 'impuestoUnico',
 'canon',
 'margenOperacion',
 'rendTarif',
 'precioPlantelSinImpuesto',
 'precioConImpuesto',
 'margenEstacionesTerrestres',
 'margenEstacionesAereas',
 'fleteEstaciones',
 'margenEnvasador',
 'margenDistribuidos',
 'margenDetallista',
 'precioConsumidorFinalGas',
 'precioFinal',
 'precioFinalSinPuntoFijo']

In [31]:
procesador_hc.ceros_nan(to_cero=True, columnas=num_col, chain=False)

{'Numero de filas': 7818,
 'Numero de columnas': 31,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 106391,
 'Dataframe':      numeroExpediente numeroResolucion fechaPublicacion alcanceGaceta  \
 0         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 1         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 2         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 3         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 4         ET-030-2026  RE-0010-IE-2026       2026-04-16            38
 ...               ...              ...              ...           ...
 7813               NA    RRG-1088-2000       2000-02-03             8
 7814               NA    RRG-1088-2000       2000-02-03             8
 7815               NA    RRG-1088-2000       2000-02-03             8
 7816               NA    RRG-1088-2000       2000-02-03             8
 7817               NA    RRG-1088-2000       2000-02-03             8

       numeroGaceta                                          producto  \
 0               69                                   Gasolina RON 95
 1               69                                   Gasolina RON 91
 2               69                      Gasolina RON 91 (pescadores)
 3               69    Diésel para uso automotriz de 50 ppm de azufre
 4               69  Diésel uso automotriz 50 ppm azufre (pescadores)
 ...            ...                                               ...
 7813            24                                 LPG -mezcla 70-30
 7814            24                                            Av-gas
 7815            24                                    Jet A- general
 7816            24                                     Nafta liviana
 7817            24                                      Nafta pesada

       tipoCambio  precioReferenciaInternacional  precioColonizado  \
 0      473.31091                          0.000           0.00000
 1      473.31091                          0.000           0.00000
 2      473.31091                          0.000           0.00000
 3      473.31091                          0.000           0.00000
 4      473.31091                          0.000           0.00000
 ...          ...                            ...               ...
 7813   299.38000                         27.006          50.85357
 7814   299.38000                         27.006          50.85357
 7815   299.38000                         27.006          50.85357
 7816   299.38000                         27.006          50.85357
 7817   299.38000                         27.006          50.85357

       otrosIngresosProrrateados  ...  margenEstacionesTerrestres  \
 0                           0.0  ...                      56.681
 1                           0.0  ...                      56.681
 2                           0.0  ...                       0.000
 3                           0.0  ...                      56.681
 4                           0.0  ...                       0.000
 ...                         ...  ...                         ...
 7813                        0.0  ...                       0.000
 7814                        0.0  ...                       0.000
 7815                        0.0  ...                       0.000
 7816                        0.0  ...                       0.000
 7817                        0.0  ...                       0.000

       margenEstacionesAereas  fleteEstaciones  margenEnvasador  \
 0                        0.0           12.773              0.0
 1                        0.0           12.773              0.0
 2                        0.0            0.000              0.0
 3                        0.0           12.773              0.0
 4                        0.0            0.000              0.0
 ...                      ...              ...              ...
 7813                     0.0            0.000              0.0
 7814                     0.0            0.000              0.0
 7815                     0.0            0.000              0.0
 7816                     0.0            0.000              0.0
 7817                     0.0            0.000              0.0

       margenDistribuidos  margenDetallista  rige  precioConsumidorFinalGas  \
 0                    0.0               0.0  True                       0.0
 1                    0.0               0.0  True                       0.0
 2                    0.0               0.0  True                       0.0
 3                    0.0               0.0  True                       0.0
 4                    0.0               0.0  True                       0.0
 ...                  ...               ...   ...                       ...
 7813                 0.0               0.0                             0.0
 7814                 0.0               0.0                             0.0
 7815                 0.0               0.0                             0.0
 7816                 0.0               0.0                             0.0
 7817                 0.0               0.0                             0.0

       precioFinal  precioFinalSinPuntoFijo
 0           632.0                564.85385
 1           628.0                560.20589
 2             0.0                  0.00000
 3           565.0                497.53335
 4             0.0                  0.00000
 ...           ...                      ...
 7813          0.0                 69.40000
 7814        191.1                186.50000
 7815        109.9                105.30000
 7816          0.0                101.40000
 7817          0.0                 99.40000

 [7818 rows x 31 columns]}

In [32]:
procesador_hc.numeric_col(reverse=True, chain=False)

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,producto,rige
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,Gasolina RON 95,True
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,Gasolina RON 91,True
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,Gasolina RON 91 (pescadores),True
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,Diésel para uso automotriz de 50 ppm de azufre,True
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,Diésel uso automotriz 50 ppm azufre (pescadores),True
...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,LPG -mezcla 70-30,
7814,NA,RRG-1088-2000,2000-02-03,8,Av-gas,
7815,NA,RRG-1088-2000,2000-02-03,8,Jet A- general,
7816,NA,RRG-1088-2000,2000-02-03,8,Nafta liviana,
7817,NA,RRG-1088-2000,2000-02-03,8,Nafta pesada,

In [33]:
procesador_hc.df

,numeroExpediente,numeroResolucion,fechaPublicacion,alcanceGaceta,numeroGaceta,producto,tipoCambio,precioReferenciaInternacional,precioColonizado,otrosIngresosProrrateados,...,margenEstacionesTerrestres,margenEstacionesAereas,fleteEstaciones,margenEnvasador,margenDistribuidos,margenDetallista,rige,precioConsumidorFinalGas,precioFinal,precioFinalSinPuntoFijo
0,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 95,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,632.0,564.85385
1,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,628.0,560.20589
2,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Gasolina RON 91 (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,0.0,0.00000
3,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel para uso automotriz de 50 ppm de azufre,473.31091,0.000,0.00000,0.0,...,56.681,0.0,12.773,0.0,0.0,0.0,True,0.0,565.0,497.53335
4,ET-030-2026,RE-0010-IE-2026,2026-04-16,38,69,Diésel uso automotriz 50 ppm azufre (pescadores),473.31091,0.000,0.00000,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,True,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,NA,RRG-1088-2000,2000-02-03,8,24,LPG -mezcla 70-30,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,69.40000
7814,NA,RRG-1088-2000,2000-02-03,8,24,Av-gas,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,191.1,186.50000
7815,NA,RRG-1088-2000,2000-02-03,8,24,Jet A- general,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,109.9,105.30000
7816,NA,RRG-1088-2000,2000-02-03,8,24,Nafta liviana,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,101.40000
7817,NA,RRG-1088-2000,2000-02-03,8,24,Nafta pesada,299.38000,27.006,50.85357,0.0,...,0.000,0.0,0.000,0.0,0.0,0.0,,0.0,0.0,99.40000

In [34]:
procesador_hc.detect_outliers(num_col, chain=False)

[{'columna': 'numeroGaceta',
  'cantidad': 0,
  'limite_inf': np.float64(-134.0),
  'limite_sup': np.float64(378.0),
  'datos': []},
 {'columna': 'tipoCambio',
  'cantidad': 679,
  'limite_inf': np.float64(403.70333999999997),
  'limite_sup': np.float64(671.8811000000001),
  'datos': [673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   673.357,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   692.85182,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   688.20818,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   400.02,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   395.8,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   392.6,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   389.34,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   385.59,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   382.33,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   377.68,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   374.38,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   369.61,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   365.09,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   353.85,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   350.39,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   346.65,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   343.4,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   340.98,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   338.52,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   336.33,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   334.35,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   331.64,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   329.9,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   327.77,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   324.12,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   322.69,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   319.48,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   318.3,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   317.21,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   315.97,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   311.73,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   305.61,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   303.86,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   300.99,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38,
   299.38]},
 {'columna': 'precioReferenciaInternacional',
  'cantidad': 70,
  'limite_inf': np.float64(-66.894845),
  'limite_sup': np.float64(174.218075),
  'datos': [175.46149,
   175.46149,
   201.71283,
   188.79646,
   200.48,
   200.48,
   200.48,
   200.48,
   200.48,
   200.48,
   200.48,
   200.556,
   200.556,
   200.48,
   200.48,
   200.633,
   200.633,
   200.556,
   200.556,
   200.48,
   200.48,
   200.48,
   200.48,
   200.648,
   200.573,
   201.613,
   200.378,
   200.378,
   204.806,
   207.39091,
   207.39091,
   207.391,
   204.26,
   206.8,
   204.807,
   204.807,
   205.128,
   205.128,
   208.74,
   211.196,
   208.74,
   206.92,
   206.92,
   204.515,
   203.878,
   210.331,
   211.89,
   204.311,
   183.645,
   183.645,
   187.257,
   196.846,
   192.942,
   192.942,
   192.942,
   187.509,
   182.618,
   193.19,
   184.609,
   193.486,
   193.486,
   196.366,
   196.366,
   200.676,
   202.03,
   185.277,
   185.277,
   177.45,
   175.288,
   175.288]},
 {'columna': 'precioColonizado',
  'cantidad': 52,
  'limite_inf': np.float64(-297.05885),
  'limite_sup': np.float64(644.13931),
  'datos': [665.2667,
   740.38965,
   740.38965,
   851.16164,
   733.80811,
   796.65883,
   733.80811,
   708.52116,
   709.60988,
   644.68868,
   716.94193,
   644.68868,
   709.60988,
   644.68868,
   716.94193,
   644.68868,
   665.86392,
   680.629,
   680.629,
   674.677,
   677.993,
   683.214,
   683.214,
   683.163,
   683.739,
   683.739,
   679.67,
   701.473,
   704.278,
   704.278,
   693.969,
   693.969,
   675.194,
   675.194,
   664.3997,
   664.3997,
   646.506,
   652.82604,
   652.82604,
   652.826,
   649.205,
   645.1828,
   645.1828,
   646.322,
   646.322,
   658.675,
   664.526,
   658.675,
   651.07,
   651.07,
   661.803,
   666.788]},
 {'columna': 'otrosIngresosProrrateados',
  'cantidad': 1880,
  'limite_inf': np.float64(0.0),
  'limite_sup': np.float64(0.0),
  'datos': [-0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,
   -0.04978,
   -0.05,
   -0.04978,
   -0.04978,

In [35]:
procesador_hc.df.columns[procesador_hc.df.columns.duplicated()]

Index([], dtype='str')

In [36]:
procesador_hc.df.columns.value_counts()[procesador_hc.df.columns.value_counts() > 1]

Series([], Name: count, dtype: int64)

In [37]:
procesador_hc.save_df("raw/aresep_apis/Hidrocarburos", chain=False)