In [1]:
import pandas as pd
from src.api import cliente_api_aresep

In [2]:
distribucion = cliente_api_aresep.ClienteAPITarifasElectricidadDistribucion()

In [3]:
dist = distribucion.obtener_datos(chain=False)

In [4]:
dist

,id_Mes,mes,anho,fecha,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,127.22,None,None,None,None,None,NaT
1,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,b. Bloque 0-3000 kWh,229770.00,None,None,None,None,None,NaT
2,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,c. Bloque mayor a 3000 kWh,76.59,None,None,None,None,None,NaT
3,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,d. Bloque 0-8 kW,95916.88,None,None,None,None,None,NaT
4,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,e. Bloque mayor a 8 kW,11989.61,None,None,None,None,None,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,8,Agosto,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [5]:
from src.eda.ProcesadorEDA import ProcesadorEDA

In [6]:
procesador_dist = ProcesadorEDA()

In [7]:
procesador_dist.df = dist

In [8]:
procesador_dist.df

,id_Mes,mes,anho,fecha,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,127.22,None,None,None,None,None,NaT
1,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,b. Bloque 0-3000 kWh,229770.00,None,None,None,None,None,NaT
2,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,c. Bloque mayor a 3000 kWh,76.59,None,None,None,None,None,NaT
3,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,d. Bloque 0-8 kW,95916.88,None,None,None,None,None,NaT
4,12,Diciembre,2019,2019-12-31,CNFL,T-CO,COMERCIOS Y SERVICIOS,e. Bloque mayor a 8 kW,11989.61,None,None,None,None,None,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,7,Julio,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,8,Agosto,2026,NaT,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,12,Diciembre,2026,NaT,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [9]:
procesador_dist.verif_consis(chain=False)

({'id_Mes': int,
  'mes': str,
  'anho': int,
  'fecha': pandas.Timestamp,
  'empresa': str,
  'tipoTarifa': str,
  'descripcionTarifa': str,
  'bloque': str,
  'tarifaPromedio': float,
  'pliego': str,
  'numeroExpediente': str,
  'numeroResolucion': str,
  'fechaPublicacion': pandas.Timestamp},
 {})

In [10]:
procesador_dist.param_set()

{'Numero de filas': 33109,
 'Numero de columnas': 15,
 'Porcentaje de nulos': 27.3683892597179,
 'Ceros totales': 114,
 'Dataframe':       id_Mes        mes  anho      fecha empresa tipoTarifa  \
 0         12  Diciembre  2019 2019-12-31    CNFL       T-CO
 1         12  Diciembre  2019 2019-12-31    CNFL       T-CO
 2         12  Diciembre  2019 2019-12-31    CNFL       T-CO
 3         12  Diciembre  2019 2019-12-31    CNFL       T-CO
 4         12  Diciembre  2019 2019-12-31    CNFL       T-CO
 ...      ...        ...   ...        ...     ...        ...
 5527       7      Julio  2026        NaT      GP     T-GPEN
 5528       7      Julio  2026        NaT      GP     T-GPEN
 5529       8     Agosto  2026        NaT      GP     T-GPEN
 5530      12  Diciembre  2026        NaT      GP      T-GPE
 5531      12  Diciembre  2026        NaT      GP      T-GPE

           descripcionTarifa                                          bloque  \
 0     COMERCIOS Y SERVICIOS  a. Consumo de Energía menor o igual a 3000 kWh
 1     COMERCIOS Y SERVICIOS                            b. Bloque 0-3000 kWh
 2     COMERCIOS Y SERVICIOS                      c. Bloque mayor a 3000 kWh
 3     COMERCIOS Y SERVICIOS                                d. Bloque 0-8 kW
 4     COMERCIOS Y SERVICIOS                          e. Bloque mayor a 8 kW
 ...                     ...                                             ...
 5527         Eólicas Nuevas                   Tarifa promedio (dólares/kWh)
 5528         Eólicas Nuevas            Tarifa límite inferior (dólares/kWh)
 5529         Eólicas Nuevas            Tarifa límite superior (dólares/kWh)
 5530     Eólicas Existentes                 Tarifa referencia (dólares/kWh)
 5531     Eólicas Existentes            Tarifa límite inferior (dólares/kWh)

       tarifaPromedio tarifa                   pliego estructuraCostos  \
 0             127.22   None                     None             None
 1          229770.00   None                     None             None
 2              76.59   None                     None             None
 3           95916.88   None                     None             None
 4           11989.61   None                     None             None
 ...              ...    ...                      ...              ...
 5527            0.10   None  Gaceta 181, Alcance 124             None
 5528            0.04   None  Gaceta 181, Alcance 124             None
 5529            0.01   None  Gaceta 181, Alcance 124             None
 5530            0.06   None     Gaceta 13, Alcance 9             None
 5531            0.02   None     Gaceta 13, Alcance 9             None

      numeroExpediente numeroResolucion fechaPublicacion
 0                None             None              NaT
 1                None             None              NaT
 2                None             None              NaT
 3                None             None              NaT
 4                None             None              NaT
 ...               ...              ...              ...
 5527      ET-051-2025  RE-0046-IE-2025       2025-09-29
 5528      ET-051-2025  RE-0046-IE-2025       2025-09-29
 5529      ET-051-2025  RE-0046-IE-2025       2025-09-29
 5530  RE-0002-IE-2025      ET-091-2024       2025-01-22
 5531  RE-0002-IE-2025      ET-091-2024       2025-01-22

 [33109 rows x 15 columns]}

In [11]:
procesador_dist.df[list(procesador_dist.col_nulls(chain=False))]

,fecha,tarifa,pliego,estructuraCostos,numeroExpediente,numeroResolucion,fechaPublicacion
0,2019-12-31,None,None,None,None,None,NaT
1,2019-12-31,None,None,None,None,None,NaT
2,2019-12-31,None,None,None,None,None,NaT
3,2019-12-31,None,None,None,None,None,NaT
4,2019-12-31,None,None,None,None,None,NaT
...,...,...,...,...,...,...,...
5527,NaT,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5528,NaT,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5529,NaT,None,"Gaceta 181, Alcance 124",None,ET-051-2025,RE-0046-IE-2025,2025-09-29
5530,NaT,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22
5531,NaT,None,"Gaceta 13, Alcance 9",None,RE-0002-IE-2025,ET-091-2024,2025-01-22

In [12]:
procesador_dist.df = procesador_dist.df[list(procesador_dist.col_nulls(reverse=True, chain=False))]

In [13]:
procesador_dist.param_set()

{'Numero de filas': 33109,
 'Numero de columnas': 8,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 114,
 'Dataframe':       id_Mes        mes  anho empresa tipoTarifa      descripcionTarifa  \
 0         12  Diciembre  2019    CNFL       T-CO  COMERCIOS Y SERVICIOS
 1         12  Diciembre  2019    CNFL       T-CO  COMERCIOS Y SERVICIOS
 2         12  Diciembre  2019    CNFL       T-CO  COMERCIOS Y SERVICIOS
 3         12  Diciembre  2019    CNFL       T-CO  COMERCIOS Y SERVICIOS
 4         12  Diciembre  2019    CNFL       T-CO  COMERCIOS Y SERVICIOS
 ...      ...        ...   ...     ...        ...                    ...
 5527       7      Julio  2026      GP     T-GPEN         Eólicas Nuevas
 5528       7      Julio  2026      GP     T-GPEN         Eólicas Nuevas
 5529       8     Agosto  2026      GP     T-GPEN         Eólicas Nuevas
 5530      12  Diciembre  2026      GP      T-GPE     Eólicas Existentes
 5531      12  Diciembre  2026      GP      T-GPE     Eólicas Existentes

                                               bloque  tarifaPromedio
 0     a. Consumo de Energía menor o igual a 3000 kWh          127.22
 1                               b. Bloque 0-3000 kWh       229770.00
 2                         c. Bloque mayor a 3000 kWh           76.59
 3                                   d. Bloque 0-8 kW        95916.88
 4                             e. Bloque mayor a 8 kW        11989.61
 ...                                              ...             ...
 5527                   Tarifa promedio (dólares/kWh)            0.10
 5528            Tarifa límite inferior (dólares/kWh)            0.04
 5529            Tarifa límite superior (dólares/kWh)            0.01
 5530                 Tarifa referencia (dólares/kWh)            0.06
 5531            Tarifa límite inferior (dólares/kWh)            0.02

 [33109 rows x 8 columns]}

In [14]:
procesador_dist.df

,id_Mes,mes,anho,empresa,tipoTarifa,descripcionTarifa,bloque,tarifaPromedio
0,12,Diciembre,2019,CNFL,T-CO,COMERCIOS Y SERVICIOS,a. Consumo de Energía menor o igual a 3000 kWh,127.22
1,12,Diciembre,2019,CNFL,T-CO,COMERCIOS Y SERVICIOS,b. Bloque 0-3000 kWh,229770.00
2,12,Diciembre,2019,CNFL,T-CO,COMERCIOS Y SERVICIOS,c. Bloque mayor a 3000 kWh,76.59
3,12,Diciembre,2019,CNFL,T-CO,COMERCIOS Y SERVICIOS,d. Bloque 0-8 kW,95916.88
4,12,Diciembre,2019,CNFL,T-CO,COMERCIOS Y SERVICIOS,e. Bloque mayor a 8 kW,11989.61
...,...,...,...,...,...,...,...,...
5527,7,Julio,2026,GP,T-GPEN,Eólicas Nuevas,Tarifa promedio (dólares/kWh),0.10
5528,7,Julio,2026,GP,T-GPEN,Eólicas Nuevas,Tarifa límite inferior (dólares/kWh),0.04
5529,8,Agosto,2026,GP,T-GPEN,Eólicas Nuevas,Tarifa límite superior (dólares/kWh),0.01
5530,12,Diciembre,2026,GP,T-GPE,Eólicas Existentes,Tarifa referencia (dólares/kWh),0.06
5531,12,Diciembre,2026,GP,T-GPE,Eólicas Existentes,Tarifa límite inferior (dólares/kWh),0.02

In [15]:
procesador_dist.save_df("raw/aresep_apis/Distribucion", chain=False)