In [1]:
import pandas as pd
from src.api import cliente_api_aresep

In [2]:
medios = cliente_api_aresep.ClienteAPITarifasPreciosMedios()

In [3]:
med = medios.obtener_datos(chain=False)

In [4]:
med

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,12,Diciembre,2019,CNFL,Alumbrado Público,0.0,7.355944e+06,4.824701e+08,4.824701e+08,65.59,65.59,IV Trimestre,Distribucion,2019 4
1,12,Diciembre,2019,COOPEALFARORUIZ,Alumbrado Público,0.0,4.230003e+04,2.022787e+06,2.022787e+06,47.82,47.82,IV Trimestre,Distribucion,2019 4
2,12,Diciembre,2019,COOPEGUANACASTE,Alumbrado Público,0.0,6.316444e+05,4.166853e+07,4.166853e+07,65.97,65.97,IV Trimestre,Distribucion,2019 4
3,12,Diciembre,2019,COOPELESCA,Alumbrado Público,0.0,7.761713e+05,5.091064e+07,5.091064e+07,65.59,65.59,IV Trimestre,Distribucion,2019 4
4,12,Diciembre,2019,COOPESANTOS,Alumbrado Público,0.0,3.054200e+05,1.993171e+07,1.993171e+07,65.26,65.26,IV Trimestre,Distribucion,2019 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1

In [5]:
from src.eda.ProcesadorEDA import ProcesadorEDA

In [6]:
procesador_med = ProcesadorEDA()

In [7]:
procesador_med.df = med

In [8]:
procesador_med.df

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,12,Diciembre,2019,CNFL,Alumbrado Público,0.0,7.355944e+06,4.824701e+08,4.824701e+08,65.59,65.59,IV Trimestre,Distribucion,2019 4
1,12,Diciembre,2019,COOPEALFARORUIZ,Alumbrado Público,0.0,4.230003e+04,2.022787e+06,2.022787e+06,47.82,47.82,IV Trimestre,Distribucion,2019 4
2,12,Diciembre,2019,COOPEGUANACASTE,Alumbrado Público,0.0,6.316444e+05,4.166853e+07,4.166853e+07,65.97,65.97,IV Trimestre,Distribucion,2019 4
3,12,Diciembre,2019,COOPELESCA,Alumbrado Público,0.0,7.761713e+05,5.091064e+07,5.091064e+07,65.59,65.59,IV Trimestre,Distribucion,2019 4
4,12,Diciembre,2019,COOPESANTOS,Alumbrado Público,0.0,3.054200e+05,1.993171e+07,1.993171e+07,65.26,65.26,IV Trimestre,Distribucion,2019 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1

In [9]:
procesador_med.verif_consis(chain=False)

({'id_Mes': int,
  'mes': str,
  'anho': int,
  'empresa': str,
  'tipoTarifa': str,
  'abonados': float,
  'ventas': float,
  'ingresoSinCVG': float,
  'ingresoConCVG': float,
  'precioMedioSinCVG': float,
  'precioMedioConCVG': float,
  'trimestre': str,
  'sistema': str,
  'trimestral': str},
 {})

In [10]:
procesador_med.param_set()

{'Numero de filas': 6030,
 'Numero de columnas': 14,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 1661,
 'Dataframe':      id_Mes        mes  anho          empresa  \
 0        12  Diciembre  2019             CNFL
 1        12  Diciembre  2019  COOPEALFARORUIZ
 2        12  Diciembre  2019  COOPEGUANACASTE
 3        12  Diciembre  2019       COOPELESCA
 4        12  Diciembre  2019      COOPESANTOS
 ..      ...        ...   ...              ...
 143       1      Enero  2026      COOPESANTOS
 144       1      Enero  2026       COOPELESCA
 145       1      Enero  2026  COOPEGUANACASTE
 146       1      Enero  2026             CNFL
 147       1      Enero  2026   TOTAL NACIONAL

                              tipoTarifa  abonados        ventas  \
 0                     Alumbrado Público       0.0  7.355944e+06
 1                     Alumbrado Público       0.0  4.230003e+04
 2                     Alumbrado Público       0.0  6.316444e+05
 3                     Alumbrado Público       0.0  7.761713e+05
 4                     Alumbrado Público       0.0  3.054200e+05
 ..                                  ...       ...           ...
 143                          Industrial     199.0  2.833962e+05
 144                          Industrial    1671.0  4.007982e+06
 145                          Industrial     231.0  1.341863e+06
 146                          Industrial    1354.0  4.582995e+06
 147  Ventas al servicio de Distribución       0.0  1.169327e+08

      ingresoSinCVG  ingresoConCVG  precioMedioSinCVG  precioMedioConCVG  \
 0     4.824701e+08   4.824701e+08              65.59              65.59
 1     2.022787e+06   2.022787e+06              47.82              47.82
 2     4.166853e+07   4.166853e+07              65.97              65.97
 3     5.091064e+07   5.091064e+07              65.59              65.59
 4     1.993171e+07   1.993171e+07              65.26              65.26
 ..             ...            ...                ...                ...
 143   4.507616e+07   4.427938e+07             159.06             156.25
 144   3.719325e+08   3.780300e+08              92.80              94.32
 145   1.255783e+08   1.395824e+08              93.59             104.02
 146   4.659484e+08   5.315566e+08             101.67             115.98
 147   4.754417e+09   4.524353e+09              40.66              38.69

         trimestre       sistema trimestral
 0    IV Trimestre  Distribucion     2019 4
 1    IV Trimestre  Distribucion     2019 4
 2    IV Trimestre  Distribucion     2019 4
 3    IV Trimestre  Distribucion     2019 4
 4    IV Trimestre  Distribucion     2019 4
 ..            ...           ...        ...
 143   I Trimestre  Distribucion     2026 1
 144   I Trimestre  Distribucion     2026 1
 145   I Trimestre  Distribucion     2026 1
 146   I Trimestre  Distribucion     2026 1
 147   I Trimestre    Generacion     2026 1

 [6030 rows x 14 columns]}

In [11]:
procesador_csv_aresep = ProcesadorEDA()
procesador_csv_aresep.csv_to_df("../data/processed/aresep_unificado_2020_2025.csv", chain=False)

{'Numero de filas': 4277,
 'Numero de columnas': 13,
 'Porcentaje de nulos': 2.095286056006187,
 'Ceros totales': 0,
 'Dataframe':       Mes   Año          Empresa             Tarifa  Abonados       Ventas  \
 0      12  2020             CNFL  ALUMBRADO PÚBLICO       NaN   6992121.03
 1      12  2020  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN     40730.50
 2      12  2020  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN    714811.65
 3      12  2020       COOPELESCA  ALUMBRADO PÚBLICO       NaN    790350.77
 4      12  2020      COOPESANTOS  ALUMBRADO PÚBLICO       NaN    333997.00
 ...   ...   ...              ...                ...       ...          ...
 4272    1  2025  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN    730942.49
 4273    1  2025  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN     33873.88
 4274    1  2025             CNFL  ALUMBRADO PÚBLICO       NaN   5403943.97
 4275    1  2025             ESPH        RESIDENCIAL   84277.0  21623025.00
 4276    1  2025            JASEC        RESIDENCIAL   95027.0  22747208.00

       Ingreso sin CVG  Ingreso con CVG  Precio Medio sin CVG  \
 0        4.343615e+08     4.343615e+08                 62.12
 1        1.669136e+06     1.669136e+06                 40.98
 2        4.072282e+07     4.072282e+07                 56.97
 3        4.456738e+07     4.456738e+07                 56.39
 4        2.057422e+07     2.057422e+07                 61.60
 ...               ...              ...                   ...
 4272     4.727736e+07     4.727736e+07                 64.68
 4273     1.691662e+06     1.691662e+06                 49.94
 4274     1.995098e+08     1.995098e+08                 36.92
 4275     1.648919e+09     1.853092e+09                 76.26
 4276     1.090946e+09     1.376691e+09                 47.96

       Precio Medio con CVG     Trimestre       Sistema Trimestral
 0                    62.12  IV Trimestre  Distribucion     2020 4
 1                    40.98  IV Trimestre  Distribucion     2020 4
 2                    56.97  IV Trimestre  Distribucion     2020 4
 3                    56.39  IV Trimestre  Distribucion     2020 4
 4                    61.60  IV Trimestre  Distribucion     2020 4
 ...                    ...           ...           ...        ...
 4272                 64.68   I Trimestre  Distribucion     2025 1
 4273                 49.94   I Trimestre  Distribucion     2025 1
 4274                 36.92   I Trimestre  Distribucion     2025 1
 4275                 85.70   I Trimestre  Distribucion     2025 1
 4276                 60.52   I Trimestre  Distribucion     2025 1

 [4277 rows x 13 columns]}

In [12]:
procesador_csv_aresep.df

,Mes,Año,Empresa,Tarifa,Abonados,Ventas,Ingreso sin CVG,Ingreso con CVG,Precio Medio sin CVG,Precio Medio con CVG,Trimestre,Sistema,Trimestral
0,12,2020,CNFL,ALUMBRADO PÚBLICO,NaN,6992121.03,4.343615e+08,4.343615e+08,62.12,62.12,IV Trimestre,Distribucion,2020 4
1,12,2020,COOPEALFARORUIZ,ALUMBRADO PÚBLICO,NaN,40730.50,1.669136e+06,1.669136e+06,40.98,40.98,IV Trimestre,Distribucion,2020 4
2,12,2020,COOPEGUANACASTE,ALUMBRADO PÚBLICO,NaN,714811.65,4.072282e+07,4.072282e+07,56.97,56.97,IV Trimestre,Distribucion,2020 4
3,12,2020,COOPELESCA,ALUMBRADO PÚBLICO,NaN,790350.77,4.456738e+07,4.456738e+07,56.39,56.39,IV Trimestre,Distribucion,2020 4
4,12,2020,COOPESANTOS,ALUMBRADO PÚBLICO,NaN,333997.00,2.057422e+07,2.057422e+07,61.60,61.60,IV Trimestre,Distribucion,2020 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,1,2025,COOPEGUANACASTE,ALUMBRADO PÚBLICO,NaN,730942.49,4.727736e+07,4.727736e+07,64.68,64.68,I Trimestre,Distribucion,2025 1
4273,1,2025,COOPEALFARORUIZ,ALUMBRADO PÚBLICO,NaN,33873.88,1.691662e+06,1.691662e+06,49.94,49.94,I Trimestre,Distribucion,2025 1
4274,1,2025,CNFL,ALUMBRADO PÚBLICO,NaN,5403943.97,1.995098e+08,1.995098e+08,36.92,36.92,I Trimestre,Distribucion,2025 1
4275,1,2025,ESPH,RESIDENCIAL,84277.0,21623025.00,1.648919e+09,1.853092e+09,76.26,85.70,I Trimestre,Distribucion,2025 1
4276,1,2025,JASEC,RESIDENCIAL,95027.0,22747208.00,1.090946e+09,1.376691e+09,47.96,60.52,I Trimestre,Distribucion,2025 1

In [13]:
procesador_med.df

,id_Mes,mes,anho,empresa,tipoTarifa,abonados,ventas,ingresoSinCVG,ingresoConCVG,precioMedioSinCVG,precioMedioConCVG,trimestre,sistema,trimestral
0,12,Diciembre,2019,CNFL,Alumbrado Público,0.0,7.355944e+06,4.824701e+08,4.824701e+08,65.59,65.59,IV Trimestre,Distribucion,2019 4
1,12,Diciembre,2019,COOPEALFARORUIZ,Alumbrado Público,0.0,4.230003e+04,2.022787e+06,2.022787e+06,47.82,47.82,IV Trimestre,Distribucion,2019 4
2,12,Diciembre,2019,COOPEGUANACASTE,Alumbrado Público,0.0,6.316444e+05,4.166853e+07,4.166853e+07,65.97,65.97,IV Trimestre,Distribucion,2019 4
3,12,Diciembre,2019,COOPELESCA,Alumbrado Público,0.0,7.761713e+05,5.091064e+07,5.091064e+07,65.59,65.59,IV Trimestre,Distribucion,2019 4
4,12,Diciembre,2019,COOPESANTOS,Alumbrado Público,0.0,3.054200e+05,1.993171e+07,1.993171e+07,65.26,65.26,IV Trimestre,Distribucion,2019 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,1,Enero,2026,COOPESANTOS,Industrial,199.0,2.833962e+05,4.507616e+07,4.427938e+07,159.06,156.25,I Trimestre,Distribucion,2026 1
144,1,Enero,2026,COOPELESCA,Industrial,1671.0,4.007982e+06,3.719325e+08,3.780300e+08,92.80,94.32,I Trimestre,Distribucion,2026 1
145,1,Enero,2026,COOPEGUANACASTE,Industrial,231.0,1.341863e+06,1.255783e+08,1.395824e+08,93.59,104.02,I Trimestre,Distribucion,2026 1
146,1,Enero,2026,CNFL,Industrial,1354.0,4.582995e+06,4.659484e+08,5.315566e+08,101.67,115.98,I Trimestre,Distribucion,2026 1
147,1,Enero,2026,TOTAL NACIONAL,Ventas al servicio de Distribución,0.0,1.169327e+08,4.754417e+09,4.524353e+09,40.66,38.69,I Trimestre,Generacion,2026 1

In [14]:
unificador = ProcesadorEDA().unificador_aresep_clima()

El archivo de clima ya existe: ../data/raw/api/clima_nasa_2020_2025.csv
No se volverÃ¡ a generar archivo desde la API.

Procesando datos...

Validación de TOTAL NACIONAL:
     Año         Mes Ingreso_empresas    Ingreso_total      Diferencia  \
0   2020  Abril       115,112,561,652  114,110,774,121  -1,001,787,531
1   2020  Agosto      106,396,646,776  105,275,967,870  -1,120,678,906
2   2020  Diciembre   100,573,115,084   99,359,850,384  -1,213,264,700
3   2020  Enero       117,727,999,358  116,980,296,648    -747,702,710
4   2020  Febrero     118,705,198,526  117,698,209,706  -1,006,988,820
5   2020  Julio       105,910,529,606  104,843,941,505  -1,066,588,101
6   2020  Junio       110,682,317,446  109,516,831,409  -1,165,486,037
7   2020  Marzo       121,225,637,977  120,112,237,151  -1,113,400,826
8   2020  Mayo        114,923,120,109  114,153,995,573    -769,124,536
9   2020  Noviembre   101,169,135,792   99,994,656,530  -1,174,479,262
10  2020  Octubre     102,300,441,492  101,126,170,086  -1,174,271,406
11  2020  Setiembre   106,200,135,229  105,189,691,585  -1,010,443,644

   Diferencia_Millones Diferencia_Porcentual%
0            -1,001.79                 -0.88%
1            -1,120.68                 -1.06%
2            -1,213.26                 -1.22%
3              -747.70                 -0.64%
4            -1,006.99                 -0.86%
5            -1,066.59                 -1.02%
6            -1,165.49                 -1.06%
7            -1,113.40                 -0.93%
8              -769.12                 -0.67%
9            -1,174.48                 -1.17%
10           -1,174.27                 -1.16%
11           -1,010.44                 -0.96%

ARESEP unificado:
   Mes   Año          Empresa             Tarifa  Abonados      Ventas  \
0   12  2020             CNFL  ALUMBRADO PÚBLICO       NaN  6992121.03
1   12  2020  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN    40730.50
2   12  2020  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN   714811.65
3   12  2020       COOPELESCA  ALUMBRADO PÚBLICO       NaN   790350.77
4   12  2020      COOPESANTOS  ALUMBRADO PÚBLICO       NaN   333997.00

   Ingreso sin CVG  Ingreso con CVG  Precio Medio sin CVG  \
0     4.343615e+08     4.343615e+08                 62.12
1     1.669136e+06     1.669136e+06                 40.98
2     4.072282e+07     4.072282e+07                 56.97
3     4.456738e+07     4.456738e+07                 56.39
4     2.057422e+07     2.057422e+07                 61.60

   Precio Medio con CVG     Trimestre       Sistema Trimestral
0                 62.12  IV Trimestre  Distribucion     2020 4
1                 40.98  IV Trimestre  Distribucion     2020 4
2                 56.97  IV Trimestre  Distribucion     2020 4
3                 56.39  IV Trimestre  Distribucion     2020 4
4                 61.60  IV Trimestre  Distribucion     2020 4
(4277, 13)

Dataset final:
   Mes   Año          Empresa             Tarifa  Abonados      Ventas  \
0   12  2020             CNFL  ALUMBRADO PÚBLICO       NaN  6992121.03
1   12  2020  COOPEALFARORUIZ  ALUMBRADO PÚBLICO       NaN    40730.50
2   12  2020  COOPEGUANACASTE  ALUMBRADO PÚBLICO       NaN   714811.65
3   12  2020       COOPELESCA  ALUMBRADO PÚBLICO       NaN   790350.77
4   12  2020      COOPESANTOS  ALUMBRADO PÚBLICO       NaN   333997.00

   Ingreso sin CVG  Ingreso con CVG  Precio Medio sin CVG  \
0     4.343615e+08     4.343615e+08                 62.12
1     1.669136e+06     1.669136e+06                 40.98
2     4.072282e+07     4.072282e+07                 56.97
3     4.456738e+07     4.456738e+07                 56.39
4     2.057422e+07     2.057422e+07                 61.60

   Precio Medio con CVG  ...    T2M_MIN  CLOUD_OD  GWETROOT         TS  \
0                 62.12  ...  16.960000  4.610000  0.910000  22.600000
1                 40.98  ...  16.960000  6.050000  0.910000  22.600000
2                 56.97  ...  21.825000  4.500000  0.855000  25.925000
3                 56.39  ...  19.956667  5.663333  0.906667  24.136667
4                 61.60  ...  16.120000  5.230000  0.960000  20.740000

   PRECTOTCORR  ALLSKY_SFC_SW_DWN          PS     T2MWET  ALLSKY_SFC_SW_DIFF  \
0     6.780000           4.688933   93.720000  21.020000            1.590333
1     6.780000           3.957600   93.720000  21.020000            1.523800
2     1.745000           5.116300  100.005000  24.335000            1.419800
3     5.836667           4.006567   97.903333  22.883333            1.554600
4    11.020000           4.645300   90.070000  19.250000            1.619300

   ALLSKY_SFC_LW_DWN
0           9.499333
1           9.360000
2           9.559200
3           9.484233
4           9.062600

[5 rows x 28 columns]
(4277, 28)