In [1]:
from src.api import cliente_api_aresep

In [2]:
zonas = cliente_api_aresep.ClienteAPIZonasConcesionPorOperador()

In [3]:
zon = zonas.obtener_datos(chain=False)

In [4]:
zon

,id_Objecto,operador,descripcion,area,coordenadas
0,1,ESPH,Limite enviado por operador,109.792479,POLYGON ((498769.51319999993 1111348.718699999...
1,2,COOPESANTOS,Limite enviado por operador,1468.551438,POLYGON ((479458.30819999985 1093005.496400000...
2,3,COOPEGUANACASTE R.L.,Limite enviado por operador,3760.164341,"POLYGON ((329648.14719999954 1170378.6995, 329..."
3,4,ICE,Limite enviado por operador,39608.051895,MULTIPOLYGON (((360855.56709999964 1226080.039...
4,7,CNFL,Limite enviado por operador,942.318932,POLYGON ((507509.7575000003 1126436.4469000008...
5,8,JASEC,Limite enviado por operador,1208.697043,POLYGON ((540962.36479999963 1060871.837200000...
6,9,COOPELESCA,Limite enviado por operador,4750.007112,POLYGON ((422198.10020000022 1168137.135399999...
7,10,COOPEALFARORUIZ,Limite enviado por operador,231.615043,POLYGON ((443233.36789999995 1133009.760500000...
8,11,ZONA EN BLANCO,Calculado por ARESEP,44.452343,MULTIPOLYGON (((351206.62459999975 1144923.119...

In [5]:
from src.eda.ProcesadorEDA import ProcesadorEDA

In [6]:
procesador_zon = ProcesadorEDA()

In [7]:
procesador_zon.df = zon

In [8]:
procesador_zon.df

,id_Objecto,operador,descripcion,area,coordenadas
0,1,ESPH,Limite enviado por operador,109.792479,POLYGON ((498769.51319999993 1111348.718699999...
1,2,COOPESANTOS,Limite enviado por operador,1468.551438,POLYGON ((479458.30819999985 1093005.496400000...
2,3,COOPEGUANACASTE R.L.,Limite enviado por operador,3760.164341,"POLYGON ((329648.14719999954 1170378.6995, 329..."
3,4,ICE,Limite enviado por operador,39608.051895,MULTIPOLYGON (((360855.56709999964 1226080.039...
4,7,CNFL,Limite enviado por operador,942.318932,POLYGON ((507509.7575000003 1126436.4469000008...
5,8,JASEC,Limite enviado por operador,1208.697043,POLYGON ((540962.36479999963 1060871.837200000...
6,9,COOPELESCA,Limite enviado por operador,4750.007112,POLYGON ((422198.10020000022 1168137.135399999...
7,10,COOPEALFARORUIZ,Limite enviado por operador,231.615043,POLYGON ((443233.36789999995 1133009.760500000...
8,11,ZONA EN BLANCO,Calculado por ARESEP,44.452343,MULTIPOLYGON (((351206.62459999975 1144923.119...

In [9]:
procesador_zon.save_df("raw/aresep_apis/Zonas", chain=False)

In [10]:
zonsplit = procesador_zon.df["coordenadas"].apply(lambda x: str(x).split())

In [11]:
zonsplit

0    [POLYGON, ((498769.51319999993, 1111348.718699...
1    [POLYGON, ((479458.30819999985, 1093005.496400...
2    [POLYGON, ((329648.14719999954, 1170378.6995,,...
3    [MULTIPOLYGON, (((360855.56709999964, 1226080....
4    [POLYGON, ((507509.7575000003, 1126436.4469000...
5    [POLYGON, ((540962.36479999963, 1060871.837200...
6    [POLYGON, ((422198.10020000022, 1168137.135399...
7    [POLYGON, ((443233.36789999995, 1133009.760500...
8    [MULTIPOLYGON, (((351206.62459999975, 1144923....
Name: coordenadas, dtype: object

In [12]:
procesador_zon.split_col(columna="coordenadas", new_col="tipo_geometria", rm=False, extract_index=0, chain=False)

,id_Objecto,operador,descripcion,area,coordenadas,tipo_geometria
0,1,ESPH,Limite enviado por operador,109.792479,POLYGON ((498769.51319999993 1111348.718699999...,POLYGON
1,2,COOPESANTOS,Limite enviado por operador,1468.551438,POLYGON ((479458.30819999985 1093005.496400000...,POLYGON
2,3,COOPEGUANACASTE R.L.,Limite enviado por operador,3760.164341,"POLYGON ((329648.14719999954 1170378.6995, 329...",POLYGON
3,4,ICE,Limite enviado por operador,39608.051895,MULTIPOLYGON (((360855.56709999964 1226080.039...,MULTIPOLYGON
4,7,CNFL,Limite enviado por operador,942.318932,POLYGON ((507509.7575000003 1126436.4469000008...,POLYGON
5,8,JASEC,Limite enviado por operador,1208.697043,POLYGON ((540962.36479999963 1060871.837200000...,POLYGON
6,9,COOPELESCA,Limite enviado por operador,4750.007112,POLYGON ((422198.10020000022 1168137.135399999...,POLYGON
7,10,COOPEALFARORUIZ,Limite enviado por operador,231.615043,POLYGON ((443233.36789999995 1133009.760500000...,POLYGON
8,11,ZONA EN BLANCO,Calculado por ARESEP,44.452343,MULTIPOLYGON (((351206.62459999975 1144923.119...,MULTIPOLYGON

In [13]:
procesador_zon.save_df("raw/aresep_apis/Zonas", chain=False)

In [16]:
procesador_zon.GestorDB.user = "sa"
procesador_zon.GestorDB.password = "progra"
procesador_zon.GestorDB.port = "5433"

In [27]:
procesador_zon.cargar_a_fact_dim(chain=False)

,objeto,filas_insertadas,mensaje
0,dim_tiempo,0,Carga de dimension tiempo completada
1,dim_empresa,0,Carga de dimension empresa completada
2,dim_tarifa,0,Carga de dimension tarifa completada
3,dim_ubicacion,0,Carga de dimension ubicacion completada
4,dim_central_electrica,0,Carga de dimension central electrica completada
5,dim_producto_hidrocarburo,0,Carga de dimension producto completada
6,dim_resolucion_hidrocarburo,0,Carga de dimension resolucion completada
7,fact_clima_mensual,0,Carga de hecho clima completada
8,fact_tarifa_electricidad,0,Carga de hecho tarifa electricidad completada
9,fact_distribucion_tarifaria,0,Carga de hecho distribucion completada
10,fact_hidrocarburos,0,Carga de hecho hidrocarburos completada
11,dim_empresa_zonas,9,Carga de operadores de zonas completada
12,dim_zona_concesion,9,Carga de zonas completada
13,bridge_empresa_zona,9,Vinculo empresa-zona completado

In [22]:
from src.datos.ETLs import ETLs

In [23]:
etl = ETLs()
etl.df = procesador_zon.df

In [24]:
etl.GestorDB.user = "sa"
etl.GestorDB.password = "progra"
etl.GestorDB.port = "5433"

In [26]:
etl.etl_stg_zonas(chain=False)

[STAGING] stg_zonas: 9/9 filas cargadas

{'tabla': 'stg_zonas',
 'filas_totales': 9,
 'filas_exitosas': 9,
 'filas_con_error': 0,
 'errores': []}